import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Extended language support - 35+ languages from Quran.com
// Removed: my, km, lo, ig, fil, gu, mr, pa, sr, hr, sl, mk, tg, sk, vi, th, hi, ky - not available correctly in API
export type Language = 
  | 'ar' | 'en' | 'fr' | 'ur' | 'id' | 'tr' | 'it' | 'de' | 'es' | 'pt' 
  | 'ru' | 'bn' | 'fa' | 'ms' | 'nl' | 'pl' | 'ro' | 'sv'
  | 'zh' | 'ja' | 'ko' | 'uz' | 'az' | 'kk' | 'tt'
  | 'bs' | 'sq' | 'bg' | 'cs' | 'uk'
  | 'am' | 'so' | 'sw' | 'ha' | 'yo' | 'ml' | 'ta' | 'te'
  | 'si' | 'ne' | 'dv';

export type LanguageRegion = 'original' | 'european' | 'asian' | 'african' | 'middleeast';

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  translationId?: number;
  translator?: string;
  source?: string;
  region: LanguageRegion;
}

export const regionLabels: Record<LanguageRegion, { ar: string; en: string }> = {
  original: { ar: 'النص الأصلي', en: 'Original Text' },
  european: { ar: 'اللغات الأوروبية', en: 'European Languages' },
  asian: { ar: 'اللغات الآسيوية', en: 'Asian Languages' },
  african: { ar: 'اللغات الأفريقية', en: 'African Languages' },
  middleeast: { ar: 'لغات الشرق الأوسط', en: 'Middle Eastern Languages' },
};

export const languages: LanguageInfo[] = [
  // Arabic (Original - no translation needed)
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', translator: 'النص الأصلي', source: 'القرآن الكريم', region: 'original' },
  
  // Major European Languages
  { code: 'en', name: 'English', nativeName: 'English', translationId: 131, translator: 'Sahih International', source: 'Dar Abul-Qasim Publishing', region: 'european' },
  { code: 'fr', name: 'French', nativeName: 'Français', translationId: 136, translator: 'Muhammad Hamidullah', source: 'King Fahd Complex', region: 'european' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', translationId: 27, translator: 'Bubenheim & Elyas', source: 'King Fahd Complex', region: 'european' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', translationId: 140, translator: 'Muhammad Isa Garcia', source: 'King Fahd Complex', region: 'european' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', translationId: 43, translator: 'Samir El-Hayek', source: 'King Fahd Complex', region: 'european' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', translationId: 153, translator: 'Hamza Roberto Piccardo', source: 'UCOII', region: 'european' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', translationId: 235, translator: 'Sofian S. Siregar', source: 'Quran.com', region: 'european' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', translationId: 42, translator: 'Józef Bielawski', source: 'King Fahd Complex', region: 'european' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', translationId: 44, translator: 'George Grigore', source: 'King Fahd Complex', region: 'european' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', translationId: 48, translator: 'Knut Bernström', source: 'King Fahd Complex', region: 'european' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', translationId: 26, translator: 'Ivan Hrbek', source: 'King Fahd Complex', region: 'european' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', translationId: 45, translator: 'Elmir Kuliev', source: 'King Fahd Complex', region: 'european' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', translationId: 217, translator: 'Mykhaylo Yakubovych', source: 'Quran.com', region: 'european' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', translationId: 237, translator: 'Tzvetan Theophanov', source: 'Quran.com', region: 'european' },
  { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski', translationId: 25, translator: 'Besim Korkut', source: 'King Fahd Complex', region: 'european' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', translationId: 89, translator: 'Sherif Ahmeti', source: 'King Fahd Complex', region: 'european' },
  
  // Middle Eastern Languages
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', translationId: 210, translator: 'Diyanet Vakfı', source: 'Diyanet İşleri', region: 'middleeast' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', translationId: 29, translator: 'Hussain Fooladvand', source: 'King Fahd Complex', region: 'middleeast' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', translationId: 23, translator: 'Vasim Mammadaliyev', source: 'King Fahd Complex', region: 'middleeast' },
  { code: 'dv', name: 'Dhivehi', nativeName: 'ދިވެހި', translationId: 86, translator: "Office of the President", source: 'Maldives Government', region: 'middleeast' },
  
  // Asian Languages
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', translationId: 234, translator: 'Fateh Muhammad Jalandhry', source: 'King Fahd Complex', region: 'asian' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', translationId: 163, translator: 'Muhiuddin Khan', source: 'King Fahd Complex', region: 'asian' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', translationId: 229, translator: 'Jan Trust Foundation', source: 'Quran.com', region: 'asian' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', translationId: 227, translator: 'Maulana Abder-Rahim', source: 'Quran.com', region: 'asian' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', translationId: 37, translator: 'Abdul-Hamid Haidar', source: 'King Fahd Complex', region: 'asian' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', translationId: 228, translator: 'Ruwwad Center', source: 'Quran.com', region: 'asian' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', translationId: 108, translator: 'Ahl Al-Hadith', source: 'Quran.com', region: 'asian' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', translationId: 134, translator: 'Kementerian Agama', source: 'Kemenag RI', region: 'asian' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', translationId: 39, translator: 'Abdullah Basmeih', source: 'King Fahd Complex', region: 'asian' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', translationId: 56, translator: 'Ma Jian', source: 'King Fahd Complex', region: 'asian' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', translationId: 35, translator: 'Ryoichi Mita', source: 'King Fahd Complex', region: 'asian' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', translationId: 36, translator: 'Korean Translation', source: 'King Fahd Complex', region: 'asian' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbek', translationId: 127, translator: 'Muhammad Sodik', source: 'King Fahd Complex', region: 'asian' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ', translationId: 222, translator: 'Khalifa Altay', source: 'King Fahd Complex', region: 'asian' },
  { code: 'tt', name: 'Tatar', nativeName: 'Татар', translationId: 53, translator: 'Yakub Ibn Nugman', source: 'King Fahd Complex', region: 'asian' },
  
  // African Languages
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', translationId: 87, translator: 'Sadiq & Sani', source: 'King Fahd Complex', region: 'african' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', translationId: 46, translator: 'Mahmud Muhammad Abduh', source: 'King Fahd Complex', region: 'african' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', translationId: 49, translator: 'Ali Muhsin Al-Barwani', source: 'King Fahd Complex', region: 'african' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa', translationId: 32, translator: 'Abubakar Mahmud Gumi', source: 'King Fahd Complex', region: 'african' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', translationId: 125, translator: 'Shaykh Abu Rahimah', source: 'Quran.com', region: 'african' },
];

// Basic UI translations (we'll keep Arabic, English as primary, others will use English fallback for UI)
const baseTranslations = {
  title: 'القرآن الكريم',
  quran: 'القرآن',
  holyQuran: 'القرآن الكريم',
  home: 'الرئيسية',
  index: 'الفهرس',
  settings: 'الإعدادات',
  search: 'البحث',
  searchPlaceholder: 'ابحث في السور...',
  athkar: 'الأذكار والأدعية',
  appearance: 'المظهر',
  lightMode: 'الوضع النهاري',
  darkMode: 'الوضع الليلي',
  language: 'اللغة',
  about: 'عن التطبيق',
  aboutText: 'تطبيق القرآن الكريم مع 14 تفسير موثوق و6 قراء مميزين. اقرأ واستمع وتدبر آيات الله.',
  quickNavigation: 'التنقل السريع',
  surahIndex: 'فهرس السور',
  browseSurahs: 'تصفح سور القرآن الكريم',
  dragToScroll: 'اسحب للتصفح أو استخدم الأسهم',
  viewFullIndex: 'عرض الفهرس الكامل',
  verse: 'آية',
  verses: 'آية',
  meccan: 'مكية',
  medinan: 'مدنية',
  available: 'متوفر',
  surah: 'سورة',
  tafsir: 'التفسير',
  tafsirSource: 'مصدر التفسير',
  compareTafsirs: 'مقارنة تفسيرين',
  hideTafsir: 'إخفاء التفسير',
  showTafsir: 'إظهار التفسير',
  benefits: 'الفوائد',
  aboutSurah: 'نبذة عن السورة',
  listenToRecitation: 'استمع لتلاوة كل آية بصوت 6 قراء مختلفين',
  reciters: 'قراء',
  features: 'مميزات التطبيق',
  allInOnePlace: 'كل ما تحتاجه في مكان واحد',
  comprehensiveApp: 'تطبيق شامل للقرآن الكريم يجمع بين القراءة والاستماع والتفسير',
  trustedTafsirs: 'تفسير موثوق',
  fromMajorBooks: 'من أمهات كتب التفسير',
  distinguishedReciters: 'قراء مميزين',
  beautifulRecitations: 'تلاوات بأصوات عذبة',
  advancedSearch: 'بحث متقدم',
  searchInVerses: 'ابحث في الآيات والتفاسير',
  favorites: 'المفضلة',
  saveYourFavorites: 'احفظ آياتك المفضلة',
  listenVerseByVerse: 'استماع آية بآية',
  orFullSurah: 'أو السورة كاملة',
  fullSurahs: 'سورة كاملة',
  uthmaniScript: 'القرآن الكريم بالرسم العثماني',
  bismillah: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
  bookOfAllah: 'كتاب الله المبين',
  readListenReflect: 'اقرأ واستمع وتدبر آيات الله بتفسير شامل من أمهات كتب التفسير',
  juz: 'جزء',
  athkarAndDuas: 'الأذكار والأدعية',
  electronicMushaf: 'المصحف الإلكتروني',
  allRightsReserved: 'جميع الحقوق محفوظة',
  trustedTafsirsList: 'التفاسير الموثوقة: ابن كثير | الطبري | السعدي | التفسير الميسر | الجلالين',
  translation: 'الترجمة',
  ttsWarning: 'تنبيه: صوت الترجمة قد لا يكون دقيقاً في نطق بعض الكلمات الإسلامية',
};

const englishTranslations = {
  title: 'The Holy Quran',
  quran: 'Quran',
  holyQuran: 'The Holy Quran',
  home: 'Home',
  index: 'Index',
  settings: 'Settings',
  search: 'Search',
  searchPlaceholder: 'Search surahs...',
  athkar: 'Athkar & Duas',
  appearance: 'Appearance',
  lightMode: 'Light Mode',
  darkMode: 'Dark Mode',
  language: 'Language',
  about: 'About App',
  aboutText: 'Quran app with 14 trusted Tafsirs and 6 distinguished reciters. Read, listen and reflect on the verses of Allah.',
  quickNavigation: 'Quick Navigation',
  surahIndex: 'Surah Index',
  browseSurahs: 'Browse the Surahs of the Holy Quran',
  dragToScroll: 'Drag to scroll or use arrows',
  viewFullIndex: 'View Full Index',
  verse: 'verse',
  verses: 'verses',
  meccan: 'Meccan',
  medinan: 'Medinan',
  available: 'Available',
  surah: 'Surah',
  tafsir: 'Tafsir',
  tafsirSource: 'Tafsir Source',
  compareTafsirs: 'Compare Tafsirs',
  hideTafsir: 'Hide Tafsir',
  showTafsir: 'Show Tafsir',
  benefits: 'Benefits',
  aboutSurah: 'About this Surah',
  listenToRecitation: 'Listen to each verse by 6 different reciters',
  reciters: 'reciters',
  features: 'App Features',
  allInOnePlace: 'Everything you need in one place',
  comprehensiveApp: 'A comprehensive Quran app combining reading, listening, and interpretation',
  trustedTafsirs: 'trusted Tafsirs',
  fromMajorBooks: 'From major Tafsir books',
  distinguishedReciters: 'distinguished reciters',
  beautifulRecitations: 'Beautiful recitations',
  advancedSearch: 'Advanced Search',
  searchInVerses: 'Search in verses and Tafsirs',
  favorites: 'Favorites',
  saveYourFavorites: 'Save your favorite verses',
  listenVerseByVerse: 'Listen verse by verse',
  orFullSurah: 'or full surah',
  fullSurahs: 'full surahs',
  uthmaniScript: 'Quran in Uthmani Script',
  bismillah: 'In the name of Allah, the Most Gracious, the Most Merciful',
  bookOfAllah: 'The Book of Allah',
  readListenReflect: 'Read, listen, and reflect on the verses of Allah with comprehensive Tafsir',
  juz: 'Juz',
  athkarAndDuas: 'Athkar & Duas',
  electronicMushaf: 'Electronic Mushaf',
  allRightsReserved: 'All rights reserved',
  trustedTafsirsList: 'Trusted Tafsirs: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
  translation: 'Translation',
  ttsWarning: 'Note: Audio may not accurately pronounce some Islamic terms',
};

type TranslationStrings = typeof baseTranslations;

export const translations: Record<Language, TranslationStrings> = {
  ar: baseTranslations,
  en: englishTranslations,
  fr: {
    ...englishTranslations,
    title: 'Le Saint Coran',
    quran: 'Coran',
    holyQuran: 'Le Saint Coran',
    home: 'Accueil',
    index: 'Index',
    settings: 'Paramètres',
    search: 'Recherche',
    searchPlaceholder: 'Rechercher des sourates...',
    language: 'Langue',
    translation: 'Traduction',
    bismillah: 'Au nom d\'Allah, le Tout Miséricordieux, le Très Miséricordieux',
  },
  ur: {
    ...englishTranslations,
    title: 'قرآن پاک',
    quran: 'قرآن',
    holyQuran: 'قرآن پاک',
    home: 'ہوم',
    index: 'اشاریہ',
    settings: 'ترتیبات',
    search: 'تلاش',
    searchPlaceholder: 'سورتیں تلاش کریں...',
    language: 'زبان',
    translation: 'ترجمہ',
    bismillah: 'بِسْمِ اللہِ الرَّحْمٰنِ الرَّحِیْمِ',
  },
  id: {
    ...englishTranslations,
    title: 'Al-Quran Al-Karim',
    quran: 'Al-Quran',
    holyQuran: 'Al-Quran Al-Karim',
    home: 'Beranda',
    index: 'Indeks',
    settings: 'Pengaturan',
    search: 'Pencarian',
    searchPlaceholder: 'Cari surah...',
    language: 'Bahasa',
    translation: 'Terjemahan',
    bismillah: 'Dengan nama Allah, Yang Maha Pengasih, Maha Penyayang',
  },
  tr: {
    ...englishTranslations,
    title: "Kur'an-ı Kerim",
    quran: "Kur'an",
    holyQuran: "Kur'an-ı Kerim",
    home: 'Ana Sayfa',
    index: 'İndeks',
    settings: 'Ayarlar',
    search: 'Arama',
    searchPlaceholder: 'Sure ara...',
    language: 'Dil',
    translation: 'Çeviri',
    bismillah: 'Rahmân ve Rahîm olan Allah\'ın adıyla',
  },
  it: {
    ...englishTranslations,
    title: 'Il Sacro Corano',
    quran: 'Corano',
    holyQuran: 'Il Sacro Corano',
    home: 'Home',
    index: 'Indice',
    settings: 'Impostazioni',
    search: 'Cerca',
    searchPlaceholder: 'Cerca sure...',
    language: 'Lingua',
    translation: 'Traduzione',
    bismillah: 'In nome di Allah, il Clemente, il Misericordioso',
  },
  // All other languages will use English as fallback for UI
  de: {
    title: 'Der Heilige Quran',
    quran: 'Quran',
    holyQuran: 'Der Heilige Quran',
    home: 'Startseite',
    index: 'Index',
    settings: 'Einstellungen',
    search: 'Suche',
    searchPlaceholder: 'Suren suchen...',
    athkar: 'Adhkar & Duas',
    appearance: 'Erscheinung',
    lightMode: 'Hellmodus',
    darkMode: 'Dunkelmodus',
    language: 'Sprache',
    about: 'Über die App',
    aboutText: 'Quran-App mit 14 vertrauenswürdigen Tafsiren und 6 ausgezeichneten Rezitatoren.',
    quickNavigation: 'Schnellnavigation',
    surahIndex: 'Surenindex',
    browseSurahs: 'Suren des Heiligen Quran durchsuchen',
    dragToScroll: 'Ziehen zum Scrollen oder Pfeile verwenden',
    viewFullIndex: 'Vollständigen Index anzeigen',
    verse: 'Vers',
    verses: 'Verse',
    meccan: 'Mekkanisch',
    medinan: 'Medinensisch',
    available: 'Verfügbar',
    surah: 'Sure',
    tafsir: 'Tafsir',
    tafsirSource: 'Tafsir-Quelle',
    compareTafsirs: 'Tafsire vergleichen',
    hideTafsir: 'Tafsir ausblenden',
    showTafsir: 'Tafsir anzeigen',
    benefits: 'Vorteile',
    aboutSurah: 'Über diese Sure',
    listenToRecitation: 'Jede Aye von 6 verschiedenen Rezitatoren anhören',
    reciters: 'Rezitatoren',
    features: 'App-Funktionen',
    allInOnePlace: 'Alles an einem Ort',
    comprehensiveApp: 'Umfassende Quran-App: Lesen, Hören und Interpretation',
    trustedTafsirs: 'vertrauenswürdige Tafsire',
    fromMajorBooks: 'Aus wichtigen Tafsir-Büchern',
    distinguishedReciters: 'ausgezeichnete Rezitatoren',
    beautifulRecitations: 'Schöne Rezitationen',
    advancedSearch: 'Erweiterte Suche',
    searchInVerses: 'In Versen und Tafsiren suchen',
    favorites: 'Favoriten',
    saveYourFavorites: 'Lieblingsverse speichern',
    listenVerseByVerse: 'Vers für Vers anhören',
    orFullSurah: 'oder vollständige Sure',
    fullSurahs: 'vollständige Suren',
    uthmaniScript: 'Quran in Uthmani-Schrift',
    bismillah: 'Im Namen Allahs, des Allerbarmers, des Barmherzigen',
    bookOfAllah: 'Das Buch Allahs',
    readListenReflect: 'Lesen, hören und über Allahs Verse nachdenken',
    juz: 'Juz',
    athkarAndDuas: 'Adhkar & Duas',
    electronicMushaf: 'Elektronischer Mushaf',
    allRightsReserved: 'Alle Rechte vorbehalten',
    trustedTafsirsList: 'Vertrauenswürdige Tafsire: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Übersetzung',
    ttsWarning: 'Hinweis: Audio spricht möglicherweise einige islamische Begriffe nicht korrekt aus',
  },
  es: {
    title: 'El Sagrado Corán',
    quran: 'Corán',
    holyQuran: 'El Sagrado Corán',
    home: 'Inicio',
    index: 'Índice',
    settings: 'Configuración',
    search: 'Buscar',
    searchPlaceholder: 'Buscar suras...',
    athkar: 'Adhkar y Duas',
    appearance: 'Apariencia',
    lightMode: 'Modo claro',
    darkMode: 'Modo oscuro',
    language: 'Idioma',
    about: 'Acerca de',
    aboutText: 'App del Corán con 14 Tafsires confiables y 6 recitadores distinguidos.',
    quickNavigation: 'Navegación rápida',
    surahIndex: 'Índice de Suras',
    browseSurahs: 'Explorar las Suras del Sagrado Corán',
    dragToScroll: 'Arrastra para desplazar o usa las flechas',
    viewFullIndex: 'Ver índice completo',
    verse: 'versículo',
    verses: 'versículos',
    meccan: 'Mecana',
    medinan: 'Medinense',
    available: 'Disponible',
    surah: 'Sura',
    tafsir: 'Tafsir',
    tafsirSource: 'Fuente del Tafsir',
    compareTafsirs: 'Comparar Tafsires',
    hideTafsir: 'Ocultar Tafsir',
    showTafsir: 'Mostrar Tafsir',
    benefits: 'Beneficios',
    aboutSurah: 'Acerca de esta Sura',
    listenToRecitation: 'Escucha cada aleya por 6 recitadores diferentes',
    reciters: 'recitadores',
    features: 'Características',
    allInOnePlace: 'Todo en un solo lugar',
    comprehensiveApp: 'App completa del Corán: lectura, escucha e interpretación',
    trustedTafsirs: 'Tafsires confiables',
    fromMajorBooks: 'De libros principales de Tafsir',
    distinguishedReciters: 'recitadores distinguidos',
    beautifulRecitations: 'Recitaciones hermosas',
    advancedSearch: 'Búsqueda avanzada',
    searchInVerses: 'Buscar en versículos y Tafsires',
    favorites: 'Favoritos',
    saveYourFavorites: 'Guarda tus versículos favoritos',
    listenVerseByVerse: 'Escuchar versículo por versículo',
    orFullSurah: 'o sura completa',
    fullSurahs: 'suras completas',
    uthmaniScript: 'Corán en escritura Uthmani',
    bismillah: 'En el nombre de Allah, el Compasivo, el Misericordioso',
    bookOfAllah: 'El Libro de Allah',
    readListenReflect: 'Lee, escucha y reflexiona sobre los versículos de Allah',
    juz: 'Juz',
    athkarAndDuas: 'Adhkar y Duas',
    electronicMushaf: 'Mushaf Electrónico',
    allRightsReserved: 'Todos los derechos reservados',
    trustedTafsirsList: 'Tafsires confiables: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Traducción',
    ttsWarning: 'Nota: El audio puede no pronunciar correctamente algunos términos islámicos',
  },
  pt: {
    title: 'O Sagrado Alcorão',
    quran: 'Alcorão',
    holyQuran: 'O Sagrado Alcorão',
    home: 'Início',
    index: 'Índice',
    settings: 'Configurações',
    search: 'Pesquisar',
    searchPlaceholder: 'Pesquisar suras...',
    athkar: 'Adhkar e Duas',
    appearance: 'Aparência',
    lightMode: 'Modo claro',
    darkMode: 'Modo escuro',
    language: 'Idioma',
    about: 'Sobre',
    aboutText: 'App do Alcorão com 14 Tafsires confiáveis e 6 recitadores distinguidos.',
    quickNavigation: 'Navegação rápida',
    surahIndex: 'Índice de Suras',
    browseSurahs: 'Explorar as Suras do Sagrado Alcorão',
    dragToScroll: 'Arraste para rolar ou use as setas',
    viewFullIndex: 'Ver índice completo',
    verse: 'versículo',
    verses: 'versículos',
    meccan: 'Mecana',
    medinan: 'Medinense',
    available: 'Disponível',
    surah: 'Sura',
    tafsir: 'Tafsir',
    tafsirSource: 'Fonte do Tafsir',
    compareTafsirs: 'Comparar Tafsires',
    hideTafsir: 'Ocultar Tafsir',
    showTafsir: 'Mostrar Tafsir',
    benefits: 'Benefícios',
    aboutSurah: 'Sobre esta Sura',
    listenToRecitation: 'Ouça cada versículo por 6 recitadores diferentes',
    reciters: 'recitadores',
    features: 'Recursos',
    allInOnePlace: 'Tudo em um só lugar',
    comprehensiveApp: 'App completo do Alcorão: leitura, audição e interpretação',
    trustedTafsirs: 'Tafsires confiáveis',
    fromMajorBooks: 'Dos principais livros de Tafsir',
    distinguishedReciters: 'recitadores distinguidos',
    beautifulRecitations: 'Recitações belas',
    advancedSearch: 'Pesquisa avançada',
    searchInVerses: 'Pesquisar em versículos e Tafsires',
    favorites: 'Favoritos',
    saveYourFavorites: 'Salve seus versículos favoritos',
    listenVerseByVerse: 'Ouvir versículo por versículo',
    orFullSurah: 'ou sura completa',
    fullSurahs: 'suras completas',
    uthmaniScript: 'Alcorão em escrita Uthmani',
    bismillah: 'Em nome de Allah, o Clemente, o Misericordioso',
    bookOfAllah: 'O Livro de Allah',
    readListenReflect: 'Leia, ouça e reflita sobre os versículos de Allah',
    juz: 'Juz',
    athkarAndDuas: 'Adhkar e Duas',
    electronicMushaf: 'Mushaf Eletrônico',
    allRightsReserved: 'Todos os direitos reservados',
    trustedTafsirsList: 'Tafsires confiáveis: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Tradução',
    ttsWarning: 'Nota: O áudio pode não pronunciar corretamente alguns termos islâmicos',
  },
  ru: {
    title: 'Священный Коран',
    quran: 'Коран',
    holyQuran: 'Священный Коран',
    home: 'Главная',
    index: 'Указатель',
    settings: 'Настройки',
    search: 'Поиск',
    searchPlaceholder: 'Искать суры...',
    athkar: 'Азкары и Дуа',
    appearance: 'Внешний вид',
    lightMode: 'Светлый режим',
    darkMode: 'Тёмный режим',
    language: 'Язык',
    about: 'О приложении',
    aboutText: 'Приложение Корана с 14 достоверными тафсирами и 6 выдающимися чтецами.',
    quickNavigation: 'Быстрая навигация',
    surahIndex: 'Указатель сур',
    browseSurahs: 'Просмотр сур Священного Корана',
    dragToScroll: 'Перетащите для прокрутки или используйте стрелки',
    viewFullIndex: 'Полный указатель',
    verse: 'аят',
    verses: 'аятов',
    meccan: 'Мекканская',
    medinan: 'Мединская',
    available: 'Доступно',
    surah: 'Сура',
    tafsir: 'Тафсир',
    tafsirSource: 'Источник тафсира',
    compareTafsirs: 'Сравнить тафсиры',
    hideTafsir: 'Скрыть тафсир',
    showTafsir: 'Показать тафсир',
    benefits: 'Польза',
    aboutSurah: 'Об этой суре',
    listenToRecitation: 'Слушайте каждый аят от 6 разных чтецов',
    reciters: 'чтецов',
    features: 'Функции',
    allInOnePlace: 'Всё в одном месте',
    comprehensiveApp: 'Полное приложение Корана: чтение, прослушивание и толкование',
    trustedTafsirs: 'достоверных тафсиров',
    fromMajorBooks: 'Из основных книг тафсира',
    distinguishedReciters: 'выдающихся чтецов',
    beautifulRecitations: 'Прекрасные чтения',
    advancedSearch: 'Расширенный поиск',
    searchInVerses: 'Поиск в аятах и тафсирах',
    favorites: 'Избранное',
    saveYourFavorites: 'Сохраните любимые аяты',
    listenVerseByVerse: 'Слушать аят за аятом',
    orFullSurah: 'или полную суру',
    fullSurahs: 'полных сур',
    uthmaniScript: 'Коран в усманском письме',
    bismillah: 'Во имя Аллаха, Милостивого, Милосердного',
    bookOfAllah: 'Книга Аллаха',
    readListenReflect: 'Читайте, слушайте и размышляйте над аятами Аллаха',
    juz: 'Джуз',
    athkarAndDuas: 'Азкары и Дуа',
    electronicMushaf: 'Электронный Мусхаф',
    allRightsReserved: 'Все права защищены',
    trustedTafsirsList: 'Достоверные тафсиры: Ибн Касир | Табари | Саади | Муяссар | Джалалейн',
    translation: 'Перевод',
    ttsWarning: 'Примечание: Аудио может неточно произносить некоторые исламские термины',
  },
  bn: {
    title: 'পবিত্র কুরআন',
    quran: 'কুরআন',
    holyQuran: 'পবিত্র কুরআন',
    home: 'হোম',
    index: 'সূচী',
    settings: 'সেটিংস',
    search: 'অনুসন্ধান',
    searchPlaceholder: 'সূরা খুঁজুন...',
    athkar: 'আযকার ও দোয়া',
    appearance: 'চেহারা',
    lightMode: 'লাইট মোড',
    darkMode: 'ডার্ক মোড',
    language: 'ভাষা',
    about: 'অ্যাপ সম্পর্কে',
    aboutText: '১৪টি বিশ্বস্ত তাফসীর এবং ৬ জন বিশিষ্ট কারীর সাথে কুরআন অ্যাপ।',
    quickNavigation: 'দ্রুত নেভিগেশন',
    surahIndex: 'সূরা সূচী',
    browseSurahs: 'পবিত্র কুরআনের সূরা ব্রাউজ করুন',
    dragToScroll: 'স্ক্রোল করতে টানুন বা তীর ব্যবহার করুন',
    viewFullIndex: 'সম্পূর্ণ সূচী দেখুন',
    verse: 'আয়াত',
    verses: 'আয়াত',
    meccan: 'মাক্কী',
    medinan: 'মাদানী',
    available: 'উপলব্ধ',
    surah: 'সূরা',
    tafsir: 'তাফসীর',
    tafsirSource: 'তাফসীর উৎস',
    compareTafsirs: 'তাফসীর তুলনা করুন',
    hideTafsir: 'তাফসীর লুকান',
    showTafsir: 'তাফসীর দেখান',
    benefits: 'ফায়দা',
    aboutSurah: 'এই সূরা সম্পর্কে',
    listenToRecitation: '৬ জন বিভিন্ন কারীর কাছ থেকে প্রতিটি আয়াত শুনুন',
    reciters: 'কারী',
    features: 'বৈশিষ্ট্য',
    allInOnePlace: 'সব এক জায়গায়',
    comprehensiveApp: 'সম্পূর্ণ কুরআন অ্যাপ: পড়া, শোনা এবং তাফসীর',
    trustedTafsirs: 'বিশ্বস্ত তাফসীর',
    fromMajorBooks: 'প্রধান তাফসীর বই থেকে',
    distinguishedReciters: 'বিশিষ্ট কারী',
    beautifulRecitations: 'সুন্দর তেলাওয়াত',
    advancedSearch: 'উন্নত অনুসন্ধান',
    searchInVerses: 'আয়াত ও তাফসীরে অনুসন্ধান করুন',
    favorites: 'প্রিয়',
    saveYourFavorites: 'আপনার প্রিয় আয়াত সংরক্ষণ করুন',
    listenVerseByVerse: 'আয়াত আয়াত শুনুন',
    orFullSurah: 'বা সম্পূর্ণ সূরা',
    fullSurahs: 'সম্পূর্ণ সূরা',
    uthmaniScript: 'উসমানী লিপিতে কুরআন',
    bismillah: 'পরম করুণাময় অতি দয়ালু আল্লাহর নামে',
    bookOfAllah: 'আল্লাহর কিতাব',
    readListenReflect: 'আল্লাহর আয়াত পড়ুন, শুনুন এবং চিন্তা করুন',
    juz: 'পারা',
    athkarAndDuas: 'আযকার ও দোয়া',
    electronicMushaf: 'ইলেকট্রনিক মুসহাফ',
    allRightsReserved: 'সর্বস্বত্ব সংরক্ষিত',
    trustedTafsirsList: 'বিশ্বস্ত তাফসীর: ইবনে কাসীর | তাবারী | সাদী | মুয়াসসার | জালালাইন',
    translation: 'অনুবাদ',
    ttsWarning: 'দ্রষ্টব্য: অডিও কিছু ইসলামী পরিভাষা সঠিকভাবে উচ্চারণ নাও করতে পারে',
  },
  fa: {
    title: 'قرآن کریم',
    quran: 'قرآن',
    holyQuran: 'قرآن کریم',
    home: 'خانه',
    index: 'فهرست',
    settings: 'تنظیمات',
    search: 'جستجو',
    searchPlaceholder: 'جستجوی سوره‌ها...',
    athkar: 'اذکار و دعا',
    appearance: 'ظاهر',
    lightMode: 'حالت روشن',
    darkMode: 'حالت تاریک',
    language: 'زبان',
    about: 'درباره برنامه',
    aboutText: 'برنامه قرآن با ۱۴ تفسیر معتبر و ۶ قاری برجسته.',
    quickNavigation: 'ناوبری سریع',
    surahIndex: 'فهرست سوره‌ها',
    browseSurahs: 'مرور سوره‌های قرآن کریم',
    dragToScroll: 'برای اسکرول بکشید یا از فلش‌ها استفاده کنید',
    viewFullIndex: 'مشاهده فهرست کامل',
    verse: 'آیه',
    verses: 'آیه',
    meccan: 'مکی',
    medinan: 'مدنی',
    available: 'موجود',
    surah: 'سوره',
    tafsir: 'تفسیر',
    tafsirSource: 'منبع تفسیر',
    compareTafsirs: 'مقایسه تفاسیر',
    hideTafsir: 'پنهان کردن تفسیر',
    showTafsir: 'نمایش تفسیر',
    benefits: 'فواید',
    aboutSurah: 'درباره این سوره',
    listenToRecitation: 'هر آیه را از ۶ قاری مختلف بشنوید',
    reciters: 'قاری',
    features: 'ویژگی‌ها',
    allInOnePlace: 'همه چیز در یک جا',
    comprehensiveApp: 'برنامه جامع قرآن: خواندن، شنیدن و تفسیر',
    trustedTafsirs: 'تفسیر معتبر',
    fromMajorBooks: 'از کتب اصلی تفسیر',
    distinguishedReciters: 'قاری برجسته',
    beautifulRecitations: 'تلاوت‌های زیبا',
    advancedSearch: 'جستجوی پیشرفته',
    searchInVerses: 'جستجو در آیات و تفاسیر',
    favorites: 'علاقه‌مندی‌ها',
    saveYourFavorites: 'آیات مورد علاقه خود را ذخیره کنید',
    listenVerseByVerse: 'آیه به آیه بشنوید',
    orFullSurah: 'یا سوره کامل',
    fullSurahs: 'سوره کامل',
    uthmaniScript: 'قرآن به خط عثمانی',
    bismillah: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِیمِ',
    bookOfAllah: 'کتاب الله',
    readListenReflect: 'آیات الله را بخوانید، بشنوید و تدبر کنید',
    juz: 'جزء',
    athkarAndDuas: 'اذکار و دعا',
    electronicMushaf: 'مصحف الکترونیکی',
    allRightsReserved: 'تمامی حقوق محفوظ است',
    trustedTafsirsList: 'تفاسیر معتبر: ابن کثیر | طبری | سعدی | میسر | جلالین',
    translation: 'ترجمه',
    ttsWarning: 'توجه: صدا ممکن است برخی اصطلاحات اسلامی را دقیق تلفظ نکند',
  },
  ms: {
    title: 'Al-Quran Al-Karim',
    quran: 'Al-Quran',
    holyQuran: 'Al-Quran Al-Karim',
    home: 'Utama',
    index: 'Indeks',
    settings: 'Tetapan',
    search: 'Carian',
    searchPlaceholder: 'Cari surah...',
    athkar: 'Zikir & Doa',
    appearance: 'Penampilan',
    lightMode: 'Mod Cerah',
    darkMode: 'Mod Gelap',
    language: 'Bahasa',
    about: 'Tentang Aplikasi',
    aboutText: 'Aplikasi Quran dengan 14 Tafsir dipercayai dan 6 Qari terbilang.',
    quickNavigation: 'Navigasi Pantas',
    surahIndex: 'Indeks Surah',
    browseSurahs: 'Layari Surah Al-Quran',
    dragToScroll: 'Seret untuk menatal atau gunakan anak panah',
    viewFullIndex: 'Lihat Indeks Penuh',
    verse: 'ayat',
    verses: 'ayat',
    meccan: 'Makkiyyah',
    medinan: 'Madaniyyah',
    available: 'Tersedia',
    surah: 'Surah',
    tafsir: 'Tafsir',
    tafsirSource: 'Sumber Tafsir',
    compareTafsirs: 'Bandingkan Tafsir',
    hideTafsir: 'Sembunyikan Tafsir',
    showTafsir: 'Tunjukkan Tafsir',
    benefits: 'Manfaat',
    aboutSurah: 'Tentang Surah Ini',
    listenToRecitation: 'Dengar setiap ayat oleh 6 Qari berbeza',
    reciters: 'Qari',
    features: 'Ciri-ciri',
    allInOnePlace: 'Semua di satu tempat',
    comprehensiveApp: 'Aplikasi Quran lengkap: baca, dengar dan tafsir',
    trustedTafsirs: 'Tafsir dipercayai',
    fromMajorBooks: 'Dari kitab tafsir utama',
    distinguishedReciters: 'Qari terbilang',
    beautifulRecitations: 'Bacaan yang indah',
    advancedSearch: 'Carian Lanjutan',
    searchInVerses: 'Cari dalam ayat dan tafsir',
    favorites: 'Kegemaran',
    saveYourFavorites: 'Simpan ayat kegemaran anda',
    listenVerseByVerse: 'Dengar ayat demi ayat',
    orFullSurah: 'atau surah penuh',
    fullSurahs: 'surah penuh',
    uthmaniScript: 'Quran dalam Tulisan Uthmani',
    bismillah: 'Dengan nama Allah, Yang Maha Pemurah, lagi Maha Mengasihani',
    bookOfAllah: 'Kitab Allah',
    readListenReflect: 'Baca, dengar dan renungkan ayat-ayat Allah',
    juz: 'Juzuk',
    athkarAndDuas: 'Zikir & Doa',
    electronicMushaf: 'Mushaf Elektronik',
    allRightsReserved: 'Hak cipta terpelihara',
    trustedTafsirsList: 'Tafsir Dipercayai: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Terjemahan',
    ttsWarning: 'Nota: Audio mungkin tidak menyebut istilah Islam dengan tepat',
  },
  nl: {
    title: 'De Heilige Koran',
    quran: 'Koran',
    holyQuran: 'De Heilige Koran',
    home: 'Home',
    index: 'Index',
    settings: 'Instellingen',
    search: 'Zoeken',
    searchPlaceholder: 'Zoek soera\'s...',
    athkar: 'Adhkar & Duas',
    appearance: 'Weergave',
    lightMode: 'Lichte modus',
    darkMode: 'Donkere modus',
    language: 'Taal',
    about: 'Over App',
    aboutText: 'Koran-app met 14 betrouwbare Tafsirs en 6 vooraanstaande recitatoren.',
    quickNavigation: 'Snelle navigatie',
    surahIndex: 'Soera-index',
    browseSurahs: 'Blader door de Soera\'s van de Heilige Koran',
    dragToScroll: 'Sleep om te scrollen of gebruik pijlen',
    viewFullIndex: 'Bekijk volledige index',
    verse: 'vers',
    verses: 'verzen',
    meccan: 'Mekkaans',
    medinan: 'Medinaans',
    available: 'Beschikbaar',
    surah: 'Soera',
    tafsir: 'Tafsir',
    tafsirSource: 'Tafsir-bron',
    compareTafsirs: 'Tafsirs vergelijken',
    hideTafsir: 'Tafsir verbergen',
    showTafsir: 'Tafsir tonen',
    benefits: 'Voordelen',
    aboutSurah: 'Over deze Soera',
    listenToRecitation: 'Luister naar elk vers door 6 verschillende recitatoren',
    reciters: 'recitatoren',
    features: 'Functies',
    allInOnePlace: 'Alles op één plek',
    comprehensiveApp: 'Complete Koran-app: lezen, luisteren en interpretatie',
    trustedTafsirs: 'betrouwbare Tafsirs',
    fromMajorBooks: 'Uit belangrijke Tafsir-boeken',
    distinguishedReciters: 'vooraanstaande recitatoren',
    beautifulRecitations: 'Mooie recitaties',
    advancedSearch: 'Geavanceerd zoeken',
    searchInVerses: 'Zoeken in verzen en Tafsirs',
    favorites: 'Favorieten',
    saveYourFavorites: 'Sla je favoriete verzen op',
    listenVerseByVerse: 'Vers voor vers luisteren',
    orFullSurah: 'of volledige soera',
    fullSurahs: 'volledige soera\'s',
    uthmaniScript: 'Koran in Uthmani-schrift',
    bismillah: 'In de naam van Allah, de Barmhartige, de Genadevolle',
    bookOfAllah: 'Het Boek van Allah',
    readListenReflect: 'Lees, luister en overdenk de verzen van Allah',
    juz: 'Juz',
    athkarAndDuas: 'Adhkar & Duas',
    electronicMushaf: 'Elektronische Mushaf',
    allRightsReserved: 'Alle rechten voorbehouden',
    trustedTafsirsList: 'Betrouwbare Tafsirs: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Vertaling',
    ttsWarning: 'Opmerking: Audio spreekt sommige islamitische termen mogelijk niet correct uit',
  },
  pl: {
    title: 'Święty Koran',
    quran: 'Koran',
    holyQuran: 'Święty Koran',
    home: 'Strona główna',
    index: 'Indeks',
    settings: 'Ustawienia',
    search: 'Szukaj',
    searchPlaceholder: 'Szukaj sur...',
    athkar: 'Adhkar i Duas',
    appearance: 'Wygląd',
    lightMode: 'Tryb jasny',
    darkMode: 'Tryb ciemny',
    language: 'Język',
    about: 'O aplikacji',
    aboutText: 'Aplikacja Koranu z 14 zaufanymi Tafsirami i 6 wyróżnionymi recytatorami.',
    quickNavigation: 'Szybka nawigacja',
    surahIndex: 'Indeks sur',
    browseSurahs: 'Przeglądaj sury Świętego Koranu',
    dragToScroll: 'Przeciągnij, aby przewinąć lub użyj strzałek',
    viewFullIndex: 'Zobacz pełny indeks',
    verse: 'werset',
    verses: 'wersetów',
    meccan: 'Mekkańska',
    medinan: 'Medyńska',
    available: 'Dostępne',
    surah: 'Sura',
    tafsir: 'Tafsir',
    tafsirSource: 'Źródło Tafsiru',
    compareTafsirs: 'Porównaj Tafsiry',
    hideTafsir: 'Ukryj Tafsir',
    showTafsir: 'Pokaż Tafsir',
    benefits: 'Korzyści',
    aboutSurah: 'O tej surze',
    listenToRecitation: 'Słuchaj każdego wersetu od 6 różnych recytatorów',
    reciters: 'recytatorów',
    features: 'Funkcje',
    allInOnePlace: 'Wszystko w jednym miejscu',
    comprehensiveApp: 'Kompleksowa aplikacja Koranu: czytanie, słuchanie i interpretacja',
    trustedTafsirs: 'zaufanych Tafsirów',
    fromMajorBooks: 'Z głównych ksiąg Tafsiru',
    distinguishedReciters: 'wyróżnionych recytatorów',
    beautifulRecitations: 'Piękne recytacje',
    advancedSearch: 'Zaawansowane wyszukiwanie',
    searchInVerses: 'Szukaj w wersetach i Tafsirach',
    favorites: 'Ulubione',
    saveYourFavorites: 'Zapisz ulubione wersety',
    listenVerseByVerse: 'Słuchaj werset po wersecie',
    orFullSurah: 'lub pełną surę',
    fullSurahs: 'pełnych sur',
    uthmaniScript: 'Koran w piśmie Uthmani',
    bismillah: 'W imię Allaha, Miłosiernego, Litościwego',
    bookOfAllah: 'Księga Allaha',
    readListenReflect: 'Czytaj, słuchaj i rozważaj wersety Allaha',
    juz: 'Dżuz',
    athkarAndDuas: 'Adhkar i Duas',
    electronicMushaf: 'Elektroniczny Mushaf',
    allRightsReserved: 'Wszelkie prawa zastrzeżone',
    trustedTafsirsList: 'Zaufane Tafsiry: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Tłumaczenie',
    ttsWarning: 'Uwaga: Audio może nieprawidłowo wymawiać niektóre terminy islamskie',
  },
  ro: {
    title: 'Sfântul Coran',
    quran: 'Coran',
    holyQuran: 'Sfântul Coran',
    home: 'Acasă',
    index: 'Index',
    settings: 'Setări',
    search: 'Căutare',
    searchPlaceholder: 'Caută sure...',
    athkar: 'Adhkar și Duas',
    appearance: 'Aspect',
    lightMode: 'Mod luminos',
    darkMode: 'Mod întunecat',
    language: 'Limbă',
    about: 'Despre aplicație',
    aboutText: 'Aplicație Coran cu 14 Tafsire de încredere și 6 recitatori distinși.',
    quickNavigation: 'Navigare rapidă',
    surahIndex: 'Index Sure',
    browseSurahs: 'Răsfoiește Surele Sfântului Coran',
    dragToScroll: 'Trage pentru a derula sau folosește săgețile',
    viewFullIndex: 'Vezi indexul complet',
    verse: 'verset',
    verses: 'versete',
    meccan: 'Meccană',
    medinan: 'Medinană',
    available: 'Disponibil',
    surah: 'Sură',
    tafsir: 'Tafsir',
    tafsirSource: 'Sursa Tafsir',
    compareTafsirs: 'Compară Tafsire',
    hideTafsir: 'Ascunde Tafsir',
    showTafsir: 'Arată Tafsir',
    benefits: 'Beneficii',
    aboutSurah: 'Despre această Sură',
    listenToRecitation: 'Ascultă fiecare verset de la 6 recitatori diferiți',
    reciters: 'recitatori',
    features: 'Caracteristici',
    allInOnePlace: 'Totul într-un singur loc',
    comprehensiveApp: 'Aplicație completă Coran: citire, ascultare și interpretare',
    trustedTafsirs: 'Tafsire de încredere',
    fromMajorBooks: 'Din cărțile principale de Tafsir',
    distinguishedReciters: 'recitatori distinși',
    beautifulRecitations: 'Recitări frumoase',
    advancedSearch: 'Căutare avansată',
    searchInVerses: 'Caută în versete și Tafsire',
    favorites: 'Favorite',
    saveYourFavorites: 'Salvează versetele tale favorite',
    listenVerseByVerse: 'Ascultă verset cu verset',
    orFullSurah: 'sau sura completă',
    fullSurahs: 'sure complete',
    uthmaniScript: 'Coran în scrierea Uthmani',
    bismillah: 'În numele lui Allah, cel Milostiv, cel Îndurător',
    bookOfAllah: 'Cartea lui Allah',
    readListenReflect: 'Citește, ascultă și meditează asupra versetelor lui Allah',
    juz: 'Juz',
    athkarAndDuas: 'Adhkar și Duas',
    electronicMushaf: 'Mushaf Electronic',
    allRightsReserved: 'Toate drepturile rezervate',
    trustedTafsirsList: 'Tafsire de încredere: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Traducere',
    ttsWarning: 'Notă: Audio-ul poate să nu pronunțe corect unii termeni islamici',
  },
  sv: {
    title: 'Den Heliga Koranen',
    quran: 'Koranen',
    holyQuran: 'Den Heliga Koranen',
    home: 'Hem',
    index: 'Index',
    settings: 'Inställningar',
    search: 'Sök',
    searchPlaceholder: 'Sök suror...',
    athkar: 'Adhkar & Duas',
    appearance: 'Utseende',
    lightMode: 'Ljust läge',
    darkMode: 'Mörkt läge',
    language: 'Språk',
    about: 'Om appen',
    aboutText: 'Koran-app med 14 pålitliga Tafsirer och 6 framstående recitatörer.',
    quickNavigation: 'Snabbnavigering',
    surahIndex: 'Sura-index',
    browseSurahs: 'Bläddra i den Heliga Koranens suror',
    dragToScroll: 'Dra för att scrolla eller använd pilarna',
    viewFullIndex: 'Visa fullständigt index',
    verse: 'vers',
    verses: 'verser',
    meccan: 'Mekkansk',
    medinan: 'Medinsk',
    available: 'Tillgänglig',
    surah: 'Sura',
    tafsir: 'Tafsir',
    tafsirSource: 'Tafsir-källa',
    compareTafsirs: 'Jämför Tafsirer',
    hideTafsir: 'Dölj Tafsir',
    showTafsir: 'Visa Tafsir',
    benefits: 'Fördelar',
    aboutSurah: 'Om denna Sura',
    listenToRecitation: 'Lyssna på varje vers av 6 olika recitatörer',
    reciters: 'recitatörer',
    features: 'Funktioner',
    allInOnePlace: 'Allt på ett ställe',
    comprehensiveApp: 'Omfattande Koran-app: läsning, lyssning och tolkning',
    trustedTafsirs: 'pålitliga Tafsirer',
    fromMajorBooks: 'Från stora Tafsir-böcker',
    distinguishedReciters: 'framstående recitatörer',
    beautifulRecitations: 'Vackra recitationer',
    advancedSearch: 'Avancerad sökning',
    searchInVerses: 'Sök i verser och Tafsirer',
    favorites: 'Favoriter',
    saveYourFavorites: 'Spara dina favoritverser',
    listenVerseByVerse: 'Lyssna vers för vers',
    orFullSurah: 'eller hela sura',
    fullSurahs: 'hela suror',
    uthmaniScript: 'Koranen i Uthmani-skrift',
    bismillah: 'I Allahs, den Nåderikes, den Barmhärtiges namn',
    bookOfAllah: 'Allahs Bok',
    readListenReflect: 'Läs, lyssna och reflektera över Allahs verser',
    juz: 'Juz',
    athkarAndDuas: 'Adhkar & Duas',
    electronicMushaf: 'Elektronisk Mushaf',
    allRightsReserved: 'Alla rättigheter reserverade',
    trustedTafsirsList: 'Pålitliga Tafsirer: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Översättning',
    ttsWarning: 'Obs: Ljudet kanske inte uttalar vissa islamiska termer korrekt',
  },
  zh: {
    title: '神圣古兰经',
    quran: '古兰经',
    holyQuran: '神圣古兰经',
    home: '首页',
    index: '目录',
    settings: '设置',
    search: '搜索',
    searchPlaceholder: '搜索章节...',
    athkar: '祈祷词',
    appearance: '外观',
    lightMode: '浅色模式',
    darkMode: '深色模式',
    language: '语言',
    about: '关于应用',
    aboutText: '古兰经应用，包含14部可信的塔夫西尔和6位杰出的诵经者。',
    quickNavigation: '快速导航',
    surahIndex: '章节目录',
    browseSurahs: '浏览神圣古兰经的章节',
    dragToScroll: '拖动滚动或使用箭头',
    viewFullIndex: '查看完整目录',
    verse: '节',
    verses: '节',
    meccan: '麦加章',
    medinan: '麦地那章',
    available: '可用',
    surah: '章',
    tafsir: '塔夫西尔',
    tafsirSource: '塔夫西尔来源',
    compareTafsirs: '比较塔夫西尔',
    hideTafsir: '隐藏塔夫西尔',
    showTafsir: '显示塔夫西尔',
    benefits: '益处',
    aboutSurah: '关于本章',
    listenToRecitation: '聆听6位不同诵经者的每节经文',
    reciters: '诵经者',
    features: '功能',
    allInOnePlace: '一站式服务',
    comprehensiveApp: '全面的古兰经应用：阅读、聆听和解读',
    trustedTafsirs: '可信的塔夫西尔',
    fromMajorBooks: '来自主要塔夫西尔书籍',
    distinguishedReciters: '杰出的诵经者',
    beautifulRecitations: '优美的诵读',
    advancedSearch: '高级搜索',
    searchInVerses: '在经文和塔夫西尔中搜索',
    favorites: '收藏',
    saveYourFavorites: '保存您喜爱的经文',
    listenVerseByVerse: '逐节聆听',
    orFullSurah: '或完整章节',
    fullSurahs: '完整章节',
    uthmaniScript: '奥斯曼体古兰经',
    bismillah: '奉至仁至慈的真主之名',
    bookOfAllah: '真主的经典',
    readListenReflect: '阅读、聆听并思考真主的经文',
    juz: '卷',
    athkarAndDuas: '祈祷词',
    electronicMushaf: '电子古兰经',
    allRightsReserved: '版权所有',
    trustedTafsirsList: '可信塔夫西尔：伊本·凯西尔 | 塔巴里 | 萨迪 | 穆亚萨尔 | 贾拉莱因',
    translation: '翻译',
    ttsWarning: '注意：音频可能无法准确发音某些伊斯兰术语',
  },
  ja: {
    title: '聖クルアーン',
    quran: 'クルアーン',
    holyQuran: '聖クルアーン',
    home: 'ホーム',
    index: '索引',
    settings: '設定',
    search: '検索',
    searchPlaceholder: 'スーラを検索...',
    athkar: 'アズカールとドゥアー',
    appearance: '外観',
    lightMode: 'ライトモード',
    darkMode: 'ダークモード',
    language: '言語',
    about: 'アプリについて',
    aboutText: '14の信頼できるタフシールと6人の著名なレシターによるクルアーンアプリ。',
    quickNavigation: 'クイックナビ',
    surahIndex: 'スーラ索引',
    browseSurahs: '聖クルアーンのスーラを閲覧',
    dragToScroll: 'ドラッグしてスクロールまたは矢印を使用',
    viewFullIndex: '完全な索引を表示',
    verse: '節',
    verses: '節',
    meccan: 'マッカ啓示',
    medinan: 'マディーナ啓示',
    available: '利用可能',
    surah: 'スーラ',
    tafsir: 'タフシール',
    tafsirSource: 'タフシールソース',
    compareTafsirs: 'タフシールを比較',
    hideTafsir: 'タフシールを隠す',
    showTafsir: 'タフシールを表示',
    benefits: '利益',
    aboutSurah: 'このスーラについて',
    listenToRecitation: '6人の異なるレシターによる各節を聴く',
    reciters: 'レシター',
    features: '機能',
    allInOnePlace: 'すべてが一箇所に',
    comprehensiveApp: '総合的なクルアーンアプリ：読む、聴く、解釈',
    trustedTafsirs: '信頼できるタフシール',
    fromMajorBooks: '主要なタフシール書籍から',
    distinguishedReciters: '著名なレシター',
    beautifulRecitations: '美しい朗読',
    advancedSearch: '高度な検索',
    searchInVerses: '節とタフシールで検索',
    favorites: 'お気に入り',
    saveYourFavorites: 'お気に入りの節を保存',
    listenVerseByVerse: '節ごとに聴く',
    orFullSurah: 'または完全なスーラ',
    fullSurahs: '完全なスーラ',
    uthmaniScript: 'ウスマーニー書体のクルアーン',
    bismillah: '慈悲深く慈愛あまねきアッラーの御名において',
    bookOfAllah: 'アッラーの書',
    readListenReflect: 'アッラーの節を読み、聴き、熟考する',
    juz: 'ジュズ',
    athkarAndDuas: 'アズカールとドゥアー',
    electronicMushaf: '電子ムスハフ',
    allRightsReserved: '全著作権所有',
    trustedTafsirsList: '信頼できるタフシール：イブン・カシール | タバリー | サアディー | ムヤッサル | ジャラーライン',
    translation: '翻訳',
    ttsWarning: '注意：音声は一部のイスラム用語を正確に発音しない場合があります',
  },
  ko: {
    title: '성 꾸란',
    quran: '꾸란',
    holyQuran: '성 꾸란',
    home: '홈',
    index: '색인',
    settings: '설정',
    search: '검색',
    searchPlaceholder: '수라 검색...',
    athkar: '아드카르 & 두아',
    appearance: '외관',
    lightMode: '라이트 모드',
    darkMode: '다크 모드',
    language: '언어',
    about: '앱 정보',
    aboutText: '14개의 신뢰할 수 있는 타프시르와 6명의 저명한 낭독자가 있는 꾸란 앱.',
    quickNavigation: '빠른 탐색',
    surahIndex: '수라 색인',
    browseSurahs: '성 꾸란의 수라 탐색',
    dragToScroll: '드래그하여 스크롤하거나 화살표 사용',
    viewFullIndex: '전체 색인 보기',
    verse: '절',
    verses: '절',
    meccan: '맥카 계시',
    medinan: '마디나 계시',
    available: '사용 가능',
    surah: '수라',
    tafsir: '타프시르',
    tafsirSource: '타프시르 출처',
    compareTafsirs: '타프시르 비교',
    hideTafsir: '타프시르 숨기기',
    showTafsir: '타프시르 표시',
    benefits: '이점',
    aboutSurah: '이 수라에 대해',
    listenToRecitation: '6명의 다른 낭독자로 각 절 듣기',
    reciters: '낭독자',
    features: '기능',
    allInOnePlace: '모든 것이 한 곳에',
    comprehensiveApp: '종합 꾸란 앱: 읽기, 듣기, 해석',
    trustedTafsirs: '신뢰할 수 있는 타프시르',
    fromMajorBooks: '주요 타프시르 서적에서',
    distinguishedReciters: '저명한 낭독자',
    beautifulRecitations: '아름다운 낭독',
    advancedSearch: '고급 검색',
    searchInVerses: '절과 타프시르에서 검색',
    favorites: '즐겨찾기',
    saveYourFavorites: '좋아하는 절 저장',
    listenVerseByVerse: '절별로 듣기',
    orFullSurah: '또는 전체 수라',
    fullSurahs: '전체 수라',
    uthmaniScript: '우스마니 서체 꾸란',
    bismillah: '자비롭고 자애로운 알라의 이름으로',
    bookOfAllah: '알라의 책',
    readListenReflect: '알라의 절을 읽고, 듣고, 숙고하세요',
    juz: '주즈',
    athkarAndDuas: '아드카르 & 두아',
    electronicMushaf: '전자 무스하프',
    allRightsReserved: '모든 권리 보유',
    trustedTafsirsList: '신뢰할 수 있는 타프시르: 이븐 카시르 | 타바리 | 사아디 | 무야사르 | 잘랄라인',
    translation: '번역',
    ttsWarning: '참고: 오디오가 일부 이슬람 용어를 정확하게 발음하지 못할 수 있습니다',
  },
  uz: {
    title: "Qur'oni Karim",
    quran: "Qur'on",
    holyQuran: "Qur'oni Karim",
    home: 'Bosh sahifa',
    index: "Ko'rsatkich",
    settings: 'Sozlamalar',
    search: 'Qidirish',
    searchPlaceholder: 'Suralarni qidirish...',
    athkar: "Zikrlar va duo'lar",
    appearance: "Ko'rinish",
    lightMode: 'Yorug rejim',
    darkMode: "Qorong'u rejim",
    language: 'Til',
    about: "Ilova haqida",
    aboutText: "14 ta ishonchli tafsir va 6 ta taniqli qorilar bilan Qur'on ilovasi.",
    quickNavigation: 'Tezkor navigatsiya',
    surahIndex: "Suralar ko'rsatkichi",
    browseSurahs: "Qur'oni Karim suralarini ko'rish",
    dragToScroll: "Aylantirsih uchun torting yoki strelkalardan foydalaning",
    viewFullIndex: "To'liq ko'rsatkichni ko'rish",
    verse: 'oyat',
    verses: 'oyat',
    meccan: 'Makka',
    medinan: 'Madina',
    available: 'Mavjud',
    surah: 'Sura',
    tafsir: 'Tafsir',
    tafsirSource: 'Tafsir manbasi',
    compareTafsirs: 'Tafsirlarni solishtirish',
    hideTafsir: 'Tafsirni yashirish',
    showTafsir: "Tafsirni ko'rsatish",
    benefits: 'Foyda',
    aboutSurah: 'Bu sura haqida',
    listenToRecitation: "Har bir oyatni 6 ta turli qoridan eshiting",
    reciters: 'qorilar',
    features: 'Xususiyatlar',
    allInOnePlace: 'Hammasi bir joyda',
    comprehensiveApp: "Keng qamrovli Qur'on ilovasi: o'qish, tinglash va tafsir",
    trustedTafsirs: 'ishonchli tafsirlar',
    fromMajorBooks: 'Asosiy tafsir kitoblaridan',
    distinguishedReciters: 'taniqli qorilar',
    beautifulRecitations: "Go'zal qiroatlar",
    advancedSearch: 'Kengaytirilgan qidiruv',
    searchInVerses: 'Oyatlar va tafsirlarda qidirish',
    favorites: 'Sevimlilar',
    saveYourFavorites: 'Sevimli oyatlaringizni saqlang',
    listenVerseByVerse: 'Oyatma-oyat tinglash',
    orFullSurah: "yoki to'liq sura",
    fullSurahs: "to'liq suralar",
    uthmaniScript: "Usmoniy yozuvida Qur'on",
    bismillah: "Mehribon va rahmli Ollohning nomi bilan",
    bookOfAllah: 'Ollohning Kitobi',
    readListenReflect: "Ollohning oyatlarini o'qing, tinglang va fikr qiling",
    juz: "Juz'",
    athkarAndDuas: "Zikrlar va duo'lar",
    electronicMushaf: 'Elektron Mushaf',
    allRightsReserved: 'Barcha huquqlar himoyalangan',
    trustedTafsirsList: "Ishonchli tafsirlar: Ibn Kasir | Tabari | Sa'diy | Muyassar | Jalalayn",
    translation: 'Tarjima',
    ttsWarning: "Eslatma: Audio ba'zi islomiy atamalarni to'g'ri talaffuz qilmasligi mumkin",
  },
  az: {
    title: 'Müqəddəs Quran',
    quran: 'Quran',
    holyQuran: 'Müqəddəs Quran',
    home: 'Ana səhifə',
    index: 'İndeks',
    settings: 'Parametrlər',
    search: 'Axtar',
    searchPlaceholder: 'Surə axtar...',
    athkar: 'Zikrlər və Dualar',
    appearance: 'Görünüş',
    lightMode: 'Açıq rejim',
    darkMode: 'Qaranlıq rejim',
    language: 'Dil',
    about: 'Tətbiq haqqında',
    aboutText: '14 etibarlı Təfsir və 6 görkəmli qari ilə Quran tətbiqi.',
    quickNavigation: 'Sürətli naviqasiya',
    surahIndex: 'Surə indeksi',
    browseSurahs: 'Müqəddəs Quranın surələrinə baxın',
    dragToScroll: 'Sürüşdürmək üçün dartın və ya oxlardan istifadə edin',
    viewFullIndex: 'Tam indeksə bax',
    verse: 'ayə',
    verses: 'ayə',
    meccan: 'Məkkə',
    medinan: 'Mədinə',
    available: 'Mövcuddur',
    surah: 'Surə',
    tafsir: 'Təfsir',
    tafsirSource: 'Təfsir mənbəsi',
    compareTafsirs: 'Təfsirləri müqayisə et',
    hideTafsir: 'Təfsiri gizlət',
    showTafsir: 'Təfsiri göstər',
    benefits: 'Faydalar',
    aboutSurah: 'Bu surə haqqında',
    listenToRecitation: 'Hər ayəni 6 fərqli qaridən dinləyin',
    reciters: 'qari',
    features: 'Xüsusiyyətlər',
    allInOnePlace: 'Hər şey bir yerdə',
    comprehensiveApp: 'Əhatəli Quran tətbiqi: oxumaq, dinləmək və təfsir',
    trustedTafsirs: 'etibarlı Təfsirlər',
    fromMajorBooks: 'Əsas Təfsir kitablarından',
    distinguishedReciters: 'görkəmli qarilər',
    beautifulRecitations: 'Gözəl tilavətlər',
    advancedSearch: 'Ətraflı axtarış',
    searchInVerses: 'Ayələrdə və Təfsirlərdə axtar',
    favorites: 'Sevimlilər',
    saveYourFavorites: 'Sevimli ayələrinizi saxlayın',
    listenVerseByVerse: 'Ayə-ayə dinlə',
    orFullSurah: 'və ya tam surə',
    fullSurahs: 'tam surələr',
    uthmaniScript: 'Osmani yazısında Quran',
    bismillah: 'Mərhəmətli və Rəhmli Allahın adı ilə',
    bookOfAllah: 'Allahın Kitabı',
    readListenReflect: 'Allahın ayələrini oxuyun, dinləyin və düşünün',
    juz: 'Cüz',
    athkarAndDuas: 'Zikrlər və Dualar',
    electronicMushaf: 'Elektron Müshəf',
    allRightsReserved: 'Bütün hüquqlar qorunur',
    trustedTafsirsList: 'Etibarlı Təfsirlər: İbn Kəsir | Təbəri | Sədi | Müyəssər | Cəlaleyn',
    translation: 'Tərcümə',
    ttsWarning: 'Qeyd: Səs bəzi İslami terminləri düzgün tələffüz etməyə bilər',
  },
  kk: {
    title: 'Құран Кәрім',
    quran: 'Құран',
    holyQuran: 'Құран Кәрім',
    home: 'Басты бет',
    index: 'Көрсеткіш',
    settings: 'Параметрлер',
    search: 'Іздеу',
    searchPlaceholder: 'Сүрелерді іздеу...',
    athkar: 'Зікірлер мен дұғалар',
    appearance: 'Көрініс',
    lightMode: 'Жарық режим',
    darkMode: 'Қараңғы режим',
    language: 'Тіл',
    about: 'Қолданба туралы',
    aboutText: '14 сенімді Тәпсір және 6 көрнекті қарилері бар Құран қолданбасы.',
    quickNavigation: 'Жылдам навигация',
    surahIndex: 'Сүре көрсеткіші',
    browseSurahs: 'Құран Кәрім сүрелерін шолу',
    dragToScroll: 'Айналдыру үшін сүйреңіз немесе көрсеткілерді қолданыңыз',
    viewFullIndex: 'Толық көрсеткішті көру',
    verse: 'аят',
    verses: 'аят',
    meccan: 'Мекке',
    medinan: 'Мәдина',
    available: 'Қолжетімді',
    surah: 'Сүре',
    tafsir: 'Тәпсір',
    tafsirSource: 'Тәпсір көзі',
    compareTafsirs: 'Тәпсірлерді салыстыру',
    hideTafsir: 'Тәпсірді жасыру',
    showTafsir: 'Тәпсірді көрсету',
    benefits: 'Пайда',
    aboutSurah: 'Бұл сүре туралы',
    listenToRecitation: 'Әр аятты 6 түрлі қаридан тыңдаңыз',
    reciters: 'қари',
    features: 'Мүмкіндіктер',
    allInOnePlace: 'Бәрі бір жерде',
    comprehensiveApp: 'Толық Құран қолданбасы: оқу, тыңдау және тәпсір',
    trustedTafsirs: 'сенімді Тәпсірлер',
    fromMajorBooks: 'Негізгі Тәпсір кітаптарынан',
    distinguishedReciters: 'көрнекті қарилер',
    beautifulRecitations: 'Әдемі қырааттар',
    advancedSearch: 'Кеңейтілген іздеу',
    searchInVerses: 'Аяттар мен Тәпсірлерден іздеу',
    favorites: 'Таңдаулылар',
    saveYourFavorites: 'Сүйікті аяттарыңызды сақтаңыз',
    listenVerseByVerse: 'Аят-аят тыңдау',
    orFullSurah: 'немесе толық сүре',
    fullSurahs: 'толық сүрелер',
    uthmaniScript: 'Османи жазуындағы Құран',
    bismillah: 'Мейірімді және рақымды Аллаһтың атымен',
    bookOfAllah: 'Аллаһтың Кітабы',
    readListenReflect: 'Аллаһтың аяттарын оқыңыз, тыңдаңыз және ой жүгіртіңіз',
    juz: 'Жүз',
    athkarAndDuas: 'Зікірлер мен дұғалар',
    electronicMushaf: 'Электронды Мұсхаф',
    allRightsReserved: 'Барлық құқықтар қорғалған',
    trustedTafsirsList: 'Сенімді Тәпсірлер: Ибн Касир | Табари | Саади | Муяссар | Жалалайн',
    translation: 'Аударма',
    ttsWarning: 'Ескерту: Аудио кейбір исламдық терминдерді дұрыс айтпауы мүмкін',
  },
  tt: {
    title: 'Коръән Кәрим',
    quran: 'Коръән',
    holyQuran: 'Коръән Кәрим',
    home: 'Баш бит',
    index: 'Күрсәткеч',
    settings: 'Көйләүләр',
    search: 'Эзләү',
    searchPlaceholder: 'Сүрәләрне эзләү...',
    athkar: 'Зекерләр һәм догалар',
    appearance: 'Күренеш',
    lightMode: 'Ачык режим',
    darkMode: 'Караңгы режим',
    language: 'Тел',
    about: 'Кушымта турында',
    aboutText: '14 ышанычлы Тәфсир һәм 6 күренекле кариләре булган Коръән кушымтасы.',
    quickNavigation: 'Тиз навигация',
    surahIndex: 'Сүрә күрсәткече',
    browseSurahs: 'Коръән Кәрим сүрәләрен карау',
    dragToScroll: 'Әйләндерү өчен тартыгыз яки уклар кулланыгыз',
    viewFullIndex: 'Тулы күрсәткечне карау',
    verse: 'аять',
    verses: 'аять',
    meccan: 'Мәккә',
    medinan: 'Мәдинә',
    available: 'Бар',
    surah: 'Сүрә',
    tafsir: 'Тәфсир',
    tafsirSource: 'Тәфсир чыганагы',
    compareTafsirs: 'Тәфсирләрне чагыштыру',
    hideTafsir: 'Тәфсирне яшерү',
    showTafsir: 'Тәфсирне күрсәтү',
    benefits: 'Файда',
    aboutSurah: 'Бу сүрә турында',
    listenToRecitation: 'Һәр аятьне 6 төрле каридан тыңлагыз',
    reciters: 'карилар',
    features: 'Үзенчәлекләр',
    allInOnePlace: 'Барысы бер урында',
    comprehensiveApp: 'Тулы Коръән кушымтасы: уку, тыңлау һәм тәфсир',
    trustedTafsirs: 'ышанычлы Тәфсирләр',
    fromMajorBooks: 'Төп Тәфсир китапларыннан',
    distinguishedReciters: 'күренекле карилар',
    beautifulRecitations: 'Матур кыйраәтләр',
    advancedSearch: 'Киңәйтелгән эзләү',
    searchInVerses: 'Аятьләр һәм Тәфсирләрдә эзләү',
    favorites: 'Сайланмалар',
    saveYourFavorites: 'Сөйкемле аятьләрегезне саклагыз',
    listenVerseByVerse: 'Аять-аять тыңлау',
    orFullSurah: 'яки тулы сүрә',
    fullSurahs: 'тулы сүрәләр',
    uthmaniScript: 'Госмани язуындагы Коръән',
    bismillah: 'Мәрхәмәтле һәм рәхимле Аллаһ исеме белән',
    bookOfAllah: 'Аллаһ Китабы',
    readListenReflect: 'Аллаһ аятьләрен укыгыз, тыңлагыз һәм фикер йөртегез',
    juz: 'Җөз',
    athkarAndDuas: 'Зекерләр һәм догалар',
    electronicMushaf: 'Электрон Мөсхәф',
    allRightsReserved: 'Барлык хокуклар сакланган',
    trustedTafsirsList: 'Ышанычлы Тәфсирләр: Ибн Кәсир | Табари | Саади | Муяссар | Җәлаләйн',
    translation: 'Тәрҗемә',
    ttsWarning: 'Искәрмә: Аудио кайбер исламча терминнарны дөрес әйтмәскә мөмкин',
  },
  bs: {
    title: 'Sveti Kuran',
    quran: 'Kuran',
    holyQuran: 'Sveti Kuran',
    home: 'Početna',
    index: 'Indeks',
    settings: 'Postavke',
    search: 'Pretraga',
    searchPlaceholder: 'Pretraži sure...',
    athkar: 'Zikrovi i dove',
    appearance: 'Izgled',
    lightMode: 'Svijetli mod',
    darkMode: 'Tamni mod',
    language: 'Jezik',
    about: 'O aplikaciji',
    aboutText: 'Kuran aplikacija sa 14 pouzdanih tefsira i 6 istaknutih učača.',
    quickNavigation: 'Brza navigacija',
    surahIndex: 'Indeks sura',
    browseSurahs: 'Pregledaj sure Svetog Kurana',
    dragToScroll: 'Povuci za pomicanje ili koristi strelice',
    viewFullIndex: 'Pogledaj puni indeks',
    verse: 'ajet',
    verses: 'ajeta',
    meccan: 'Mekanska',
    medinan: 'Medinska',
    available: 'Dostupno',
    surah: 'Sura',
    tafsir: 'Tefsir',
    tafsirSource: 'Izvor tefsira',
    compareTafsirs: 'Uporedi tefsire',
    hideTafsir: 'Sakrij tefsir',
    showTafsir: 'Prikaži tefsir',
    benefits: 'Koristi',
    aboutSurah: 'O ovoj suri',
    listenToRecitation: 'Slušaj svaki ajet od 6 različitih učača',
    reciters: 'učača',
    features: 'Funkcije',
    allInOnePlace: 'Sve na jednom mjestu',
    comprehensiveApp: 'Sveobuhvatna Kuran aplikacija: čitanje, slušanje i tumačenje',
    trustedTafsirs: 'pouzdanih tefsira',
    fromMajorBooks: 'Iz glavnih tefsirskih knjiga',
    distinguishedReciters: 'istaknutih učača',
    beautifulRecitations: 'Lijepa učenja',
    advancedSearch: 'Napredna pretraga',
    searchInVerses: 'Pretraži u ajetima i tefsirima',
    favorites: 'Omiljeno',
    saveYourFavorites: 'Sačuvaj omiljene ajete',
    listenVerseByVerse: 'Slušaj ajet po ajet',
    orFullSurah: 'ili cijelu suru',
    fullSurahs: 'cijelih sura',
    uthmaniScript: 'Kuran u osmanskom pismu',
    bismillah: 'U ime Allaha, Milostivog, Samilosnog',
    bookOfAllah: 'Allahova Knjiga',
    readListenReflect: 'Čitaj, slušaj i razmišljaj o Allahovim ajetima',
    juz: 'Džuz',
    athkarAndDuas: 'Zikrovi i dove',
    electronicMushaf: 'Elektronski Mushaf',
    allRightsReserved: 'Sva prava zadržana',
    trustedTafsirsList: 'Pouzdani tefsiri: Ibn Kesir | Taberi | Sadi | Mujesar | Dželalejn',
    translation: 'Prijevod',
    ttsWarning: 'Napomena: Audio možda neće ispravno izgovoriti neke islamske pojmove',
  },
  sq: {
    title: 'Kurani i Shenjtë',
    quran: 'Kurani',
    holyQuran: 'Kurani i Shenjtë',
    home: 'Kryefaqja',
    index: 'Indeksi',
    settings: 'Cilësimet',
    search: 'Kërko',
    searchPlaceholder: 'Kërko sure...',
    athkar: 'Dhikër dhe Dua',
    appearance: 'Pamja',
    lightMode: 'Modaliteti i ndritshëm',
    darkMode: 'Modaliteti i errët',
    language: 'Gjuha',
    about: 'Rreth aplikacionit',
    aboutText: 'Aplikacion Kurani me 14 Tefsire të besueshme dhe 6 lexues të shquar.',
    quickNavigation: 'Navigim i shpejtë',
    surahIndex: 'Indeksi i sureve',
    browseSurahs: 'Shfletoni suret e Kuranit të Shenjtë',
    dragToScroll: 'Tërhiq për të lëvizur ose përdor shigjetat',
    viewFullIndex: 'Shiko indeksin e plotë',
    verse: 'ajet',
    verses: 'ajete',
    meccan: 'Mekase',
    medinan: 'Medinase',
    available: 'E disponueshme',
    surah: 'Sure',
    tafsir: 'Tefsir',
    tafsirSource: 'Burimi i Tefsirit',
    compareTafsirs: 'Krahaso Tefsiret',
    hideTafsir: 'Fshih Tefsirin',
    showTafsir: 'Shfaq Tefsirin',
    benefits: 'Përfitime',
    aboutSurah: 'Rreth kësaj sureje',
    listenToRecitation: 'Dëgjo çdo ajet nga 6 lexues të ndryshëm',
    reciters: 'lexues',
    features: 'Veçoritë',
    allInOnePlace: 'Gjithçka në një vend',
    comprehensiveApp: 'Aplikacion i plotë Kurani: lexim, dëgjim dhe interpretim',
    trustedTafsirs: 'Tefsire të besueshme',
    fromMajorBooks: 'Nga librat kryesorë të Tefsirit',
    distinguishedReciters: 'lexues të shquar',
    beautifulRecitations: 'Lexime të bukura',
    advancedSearch: 'Kërkim i avancuar',
    searchInVerses: 'Kërko në ajete dhe Tefsire',
    favorites: 'Të preferuarat',
    saveYourFavorites: 'Ruaj ajetet e preferuara',
    listenVerseByVerse: 'Dëgjo ajet për ajet',
    orFullSurah: 'ose sureja e plotë',
    fullSurahs: 'sure të plota',
    uthmaniScript: 'Kurani në shkrimin Uthmani',
    bismillah: 'Në emër të Allahut, Mëshiruesit, Mëshirëbërësit',
    bookOfAllah: 'Libri i Allahut',
    readListenReflect: 'Lexo, dëgjo dhe reflekto mbi ajetet e Allahut',
    juz: 'Xhuz',
    athkarAndDuas: 'Dhikër dhe Dua',
    electronicMushaf: 'Mus\'hafi Elektronik',
    allRightsReserved: 'Të gjitha të drejtat e rezervuara',
    trustedTafsirsList: 'Tefsire të besueshme: Ibn Kethir | Taberi | Sadi | Mujesar | Xhelalejn',
    translation: 'Përkthimi',
    ttsWarning: 'Shënim: Audio mund të mos i shqiptojë saktësisht disa terma islamike',
  },
  bg: {
    title: 'Свещеният Коран',
    quran: 'Коран',
    holyQuran: 'Свещеният Коран',
    home: 'Начало',
    index: 'Индекс',
    settings: 'Настройки',
    search: 'Търсене',
    searchPlaceholder: 'Търси сури...',
    athkar: 'Азкар и Дуа',
    appearance: 'Външен вид',
    lightMode: 'Светъл режим',
    darkMode: 'Тъмен режим',
    language: 'Език',
    about: 'За приложението',
    aboutText: 'Коран приложение с 14 надеждни Тафсира и 6 изтъкнати четци.',
    quickNavigation: 'Бърза навигация',
    surahIndex: 'Индекс на сури',
    browseSurahs: 'Разгледай сурите на Свещения Коран',
    dragToScroll: 'Плъзни за превъртане или използвай стрелките',
    viewFullIndex: 'Виж пълния индекс',
    verse: 'аят',
    verses: 'аята',
    meccan: 'Меканска',
    medinan: 'Мединска',
    available: 'Налично',
    surah: 'Сура',
    tafsir: 'Тафсир',
    tafsirSource: 'Източник на Тафсир',
    compareTafsirs: 'Сравни Тафсири',
    hideTafsir: 'Скрий Тафсир',
    showTafsir: 'Покажи Тафсир',
    benefits: 'Ползи',
    aboutSurah: 'За тази сура',
    listenToRecitation: 'Слушай всеки аят от 6 различни четци',
    reciters: 'четци',
    features: 'Функции',
    allInOnePlace: 'Всичко на едно място',
    comprehensiveApp: 'Цялостно Коран приложение: четене, слушане и тълкуване',
    trustedTafsirs: 'надеждни Тафсира',
    fromMajorBooks: 'От основните книги на Тафсир',
    distinguishedReciters: 'изтъкнати четци',
    beautifulRecitations: 'Красиви четения',
    advancedSearch: 'Разширено търсене',
    searchInVerses: 'Търси в аяти и Тафсири',
    favorites: 'Любими',
    saveYourFavorites: 'Запази любимите си аяти',
    listenVerseByVerse: 'Слушай аят по аят',
    orFullSurah: 'или пълна сура',
    fullSurahs: 'пълни сури',
    uthmaniScript: 'Коран в Османско писмо',
    bismillah: 'В името на Аллах, Милостивия, Милосърдния',
    bookOfAllah: 'Книгата на Аллах',
    readListenReflect: 'Чети, слушай и размишлявай върху аятите на Аллах',
    juz: 'Джуз',
    athkarAndDuas: 'Азкар и Дуа',
    electronicMushaf: 'Електронен Мусхаф',
    allRightsReserved: 'Всички права запазени',
    trustedTafsirsList: 'Надеждни Тафсири: Ибн Касир | Табари | Саади | Муясар | Джалалейн',
    translation: 'Превод',
    ttsWarning: 'Забележка: Аудиото може да не произнася правилно някои ислямски термини',
  },
  cs: {
    title: 'Svatý Korán',
    quran: 'Korán',
    holyQuran: 'Svatý Korán',
    home: 'Domů',
    index: 'Rejstřík',
    settings: 'Nastavení',
    search: 'Hledat',
    searchPlaceholder: 'Hledat súry...',
    athkar: 'Adhkár a Dua',
    appearance: 'Vzhled',
    lightMode: 'Světlý režim',
    darkMode: 'Tmavý režim',
    language: 'Jazyk',
    about: 'O aplikaci',
    aboutText: 'Aplikace Koránu se 14 důvěryhodnými Tafsíry a 6 významnými recitátory.',
    quickNavigation: 'Rychlá navigace',
    surahIndex: 'Rejstřík súr',
    browseSurahs: 'Procházet súry Svatého Koránu',
    dragToScroll: 'Táhni pro posouvání nebo použij šipky',
    viewFullIndex: 'Zobrazit úplný rejstřík',
    verse: 'verš',
    verses: 'veršů',
    meccan: 'Mekkánská',
    medinan: 'Medínská',
    available: 'Dostupné',
    surah: 'Súra',
    tafsir: 'Tafsír',
    tafsirSource: 'Zdroj Tafsíru',
    compareTafsirs: 'Porovnat Tafsíry',
    hideTafsir: 'Skrýt Tafsír',
    showTafsir: 'Zobrazit Tafsír',
    benefits: 'Přínosy',
    aboutSurah: 'O této súře',
    listenToRecitation: 'Poslouchej každý verš od 6 různých recitátorů',
    reciters: 'recitátorů',
    features: 'Funkce',
    allInOnePlace: 'Vše na jednom místě',
    comprehensiveApp: 'Komplexní aplikace Koránu: čtení, poslech a výklad',
    trustedTafsirs: 'důvěryhodných Tafsírů',
    fromMajorBooks: 'Z hlavních knih Tafsíru',
    distinguishedReciters: 'významných recitátorů',
    beautifulRecitations: 'Krásné recitace',
    advancedSearch: 'Pokročilé vyhledávání',
    searchInVerses: 'Hledat ve verších a Tafsírech',
    favorites: 'Oblíbené',
    saveYourFavorites: 'Ulož své oblíbené verše',
    listenVerseByVerse: 'Poslouchej verš po verši',
    orFullSurah: 'nebo celou súru',
    fullSurahs: 'celých súr',
    uthmaniScript: 'Korán v usmánském písmu',
    bismillah: 'Ve jménu Alláha, Milosrdného, Slitovného',
    bookOfAllah: 'Kniha Alláha',
    readListenReflect: 'Čti, poslouchej a rozjímej nad verši Alláha',
    juz: 'Džuz',
    athkarAndDuas: 'Adhkár a Dua',
    electronicMushaf: 'Elektronický Mushaf',
    allRightsReserved: 'Všechna práva vyhrazena',
    trustedTafsirsList: 'Důvěryhodné Tafsíry: Ibn Kathír | Tabarí | Saadí | Muyassar | Džalálajn',
    translation: 'Překlad',
    ttsWarning: 'Poznámka: Zvuk nemusí správně vyslovovat některé islámské termíny',
  },
  uk: {
    title: 'Священний Коран',
    quran: 'Коран',
    holyQuran: 'Священний Коран',
    home: 'Головна',
    index: 'Покажчик',
    settings: 'Налаштування',
    search: 'Пошук',
    searchPlaceholder: 'Шукати сури...',
    athkar: 'Азкари та Дуа',
    appearance: 'Зовнішній вигляд',
    lightMode: 'Світлий режим',
    darkMode: 'Темний режим',
    language: 'Мова',
    about: 'Про додаток',
    aboutText: 'Додаток Корану з 14 надійними Тафсірами та 6 видатними читцями.',
    quickNavigation: 'Швидка навігація',
    surahIndex: 'Покажчик сур',
    browseSurahs: 'Перегляд сур Священного Корану',
    dragToScroll: 'Перетягніть для прокручування або використовуйте стрілки',
    viewFullIndex: 'Переглянути повний покажчик',
    verse: 'аят',
    verses: 'аятів',
    meccan: 'Мекканська',
    medinan: 'Мединська',
    available: 'Доступно',
    surah: 'Сура',
    tafsir: 'Тафсір',
    tafsirSource: 'Джерело Тафсіру',
    compareTafsirs: 'Порівняти Тафсіри',
    hideTafsir: 'Сховати Тафсір',
    showTafsir: 'Показати Тафсір',
    benefits: 'Користь',
    aboutSurah: 'Про цю суру',
    listenToRecitation: 'Слухайте кожен аят від 6 різних читців',
    reciters: 'читців',
    features: 'Функції',
    allInOnePlace: 'Все в одному місці',
    comprehensiveApp: 'Повний додаток Корану: читання, прослуховування та тлумачення',
    trustedTafsirs: 'надійних Тафсірів',
    fromMajorBooks: 'З основних книг Тафсіру',
    distinguishedReciters: 'видатних читців',
    beautifulRecitations: 'Прекрасні читання',
    advancedSearch: 'Розширений пошук',
    searchInVerses: 'Пошук в аятах та Тафсірах',
    favorites: 'Обране',
    saveYourFavorites: 'Збережіть улюблені аяти',
    listenVerseByVerse: 'Слухати аят за аятом',
    orFullSurah: 'або повну суру',
    fullSurahs: 'повних сур',
    uthmaniScript: 'Коран в османському письмі',
    bismillah: 'В ім\'я Аллага, Милостивого, Милосердного',
    bookOfAllah: 'Книга Аллага',
    readListenReflect: 'Читайте, слухайте та роздумуйте над аятами Аллага',
    juz: 'Джуз',
    athkarAndDuas: 'Азкари та Дуа',
    electronicMushaf: 'Електронний Мусхаф',
    allRightsReserved: 'Усі права захищені',
    trustedTafsirsList: 'Надійні Тафсіри: Ібн Касір | Табарі | Сааді | Муяссар | Джалалейн',
    translation: 'Переклад',
    ttsWarning: 'Примітка: Аудіо може неточно вимовляти деякі ісламські терміни',
  },
  am: {
    title: 'ቅዱስ ቁርዓን',
    quran: 'ቁርዓን',
    holyQuran: 'ቅዱስ ቁርዓን',
    home: 'መነሻ',
    index: 'ማውጫ',
    settings: 'ቅንብሮች',
    search: 'ፈልግ',
    searchPlaceholder: 'ሱራዎችን ፈልግ...',
    athkar: 'አዝካር እና ዱዓ',
    appearance: 'መልክ',
    lightMode: 'ብርሃን ሁነታ',
    darkMode: 'ጨለማ ሁነታ',
    language: 'ቋንቋ',
    about: 'ስለ መተግበሪያው',
    aboutText: '14 ታማኝ ተፍሲር እና 6 ታዋቂ አንባቢዎች ያሉት የቁርዓን መተግበሪያ።',
    quickNavigation: 'ፈጣን አሰሳ',
    surahIndex: 'ሱራ ማውጫ',
    browseSurahs: 'የቅዱስ ቁርዓን ሱራዎችን ያስሱ',
    dragToScroll: 'ለማሸብለል ይጎትቱ ወይም ቀስቶችን ይጠቀሙ',
    viewFullIndex: 'ሙሉ ማውጫ ይመልከቱ',
    verse: 'አያ',
    verses: 'አያዎች',
    meccan: 'መካዊ',
    medinan: 'መዲናዊ',
    available: 'ይገኛል',
    surah: 'ሱራ',
    tafsir: 'ተፍሲር',
    tafsirSource: 'የተፍሲር ምንጭ',
    compareTafsirs: 'ተፍሲሮችን አወዳድር',
    hideTafsir: 'ተፍሲርን ደብቅ',
    showTafsir: 'ተፍሲርን አሳይ',
    benefits: 'ጥቅሞች',
    aboutSurah: 'ስለዚህ ሱራ',
    listenToRecitation: 'እያንዳንዱን አያ ከ6 የተለያዩ አንባቢዎች ያዳምጡ',
    reciters: 'አንባቢዎች',
    features: 'ባህሪያት',
    allInOnePlace: 'ሁሉም በአንድ ቦታ',
    comprehensiveApp: 'ሁሉን አቀፍ ቁርዓን መተግበሪያ: ማንበብ፣ ማዳመጥ እና ትርጓሜ',
    trustedTafsirs: 'ታማኝ ተፍሲሮች',
    fromMajorBooks: 'ከዋና ተፍሲር መጻሕፍት',
    distinguishedReciters: 'ታዋቂ አንባቢዎች',
    beautifulRecitations: 'ቆንጆ ንባቦች',
    advancedSearch: 'የተራቀቀ ፍለጋ',
    searchInVerses: 'በአያዎች እና ተፍሲሮች ውስጥ ፈልግ',
    favorites: 'ተወዳጆች',
    saveYourFavorites: 'ተወዳጅ አያዎችዎን ያስቀምጡ',
    listenVerseByVerse: 'አያ በአያ ያዳምጡ',
    orFullSurah: 'ወይም ሙሉ ሱራ',
    fullSurahs: 'ሙሉ ሱራዎች',
    uthmaniScript: 'በኡስማኒ ጽሕፈት ቁርዓን',
    bismillah: 'በአላህ ስም እጅግ በጣም ርኅሩኅ እጅግ በጣም አዛኝ',
    bookOfAllah: 'የአላህ መጽሐፍ',
    readListenReflect: 'የአላህን አያዎች አንብቡ፣ አዳምጡ እና አስተነትኑ',
    juz: 'ጁዝ',
    athkarAndDuas: 'አዝካር እና ዱዓ',
    electronicMushaf: 'ኤሌክትሮኒክ ሙስሐፍ',
    allRightsReserved: 'ሁሉም መብቶች የተጠበቁ ናቸው',
    trustedTafsirsList: 'ታማኝ ተፍሲሮች: ኢብን ከሲር | ጠበሪ | ሳዕዲ | ሙየሰር | ጀላለይን',
    translation: 'ትርጉም',
    ttsWarning: 'ማስታወሻ: ድምጹ አንዳንድ እስላማዊ ቃላትን በትክክል ላይናገር ይችላል',
  },
  so: {
    title: 'Quraanka Kariimka',
    quran: 'Quraanka',
    holyQuran: 'Quraanka Kariimka',
    home: 'Bogga Hore',
    index: 'Tusmada',
    settings: 'Dejinta',
    search: 'Raadi',
    searchPlaceholder: 'Raadi suuradaha...',
    athkar: 'Xasuusta iyo Ducada',
    appearance: 'Muuqaalka',
    lightMode: 'Qaab Iftiinka',
    darkMode: 'Qaab Mugdiga',
    language: 'Luuqadda',
    about: 'Ku saabsan App-ka',
    aboutText: 'App-ka Quraanka oo leh 14 Tafsiir la aamino iyo 6 akhristayaal caan ah.',
    quickNavigation: 'Hagid Degdeg ah',
    surahIndex: 'Tusmada Suuradaha',
    browseSurahs: 'Eeg Suuradaha Quraanka Kariimka',
    dragToScroll: 'U jiid si aad u duuduubto ama isticmaal fallaadhaha',
    viewFullIndex: 'Arag tusmada buuxda',
    verse: 'aayad',
    verses: 'aayado',
    meccan: 'Maki',
    medinan: 'Madani',
    available: 'Diyaar',
    surah: 'Suuro',
    tafsir: 'Tafsiir',
    tafsirSource: 'Xigashada Tafsiirka',
    compareTafsirs: 'Isbarbar dhig Tafsiirrada',
    hideTafsir: 'Qari Tafsiirka',
    showTafsir: 'Tus Tafsiirka',
    benefits: 'Faa\'iidooyinka',
    aboutSurah: 'Ku saabsan Suuradan',
    listenToRecitation: 'Dhageyso aayad kasta oo ay akhristaan 6 akhristayaal kala duwan',
    reciters: 'akhristayaal',
    features: 'Astaamaha',
    allInOnePlace: 'Wax walba oo meel ku yaal',
    comprehensiveApp: 'App Quraan oo dhammaystiran: akhriska, dhageysiga iyo fasiraadda',
    trustedTafsirs: 'Tafsiir la aamino',
    fromMajorBooks: 'Buugaagta waaweyn ee Tafsiirka',
    distinguishedReciters: 'akhristayaal caan ah',
    beautifulRecitations: 'Akhriskii quruxda badnaa',
    advancedSearch: 'Raadinta Horumarsan',
    searchInVerses: 'Raadi aayado iyo Tafsiirro',
    favorites: 'Kuwa La Jecel Yahay',
    saveYourFavorites: 'Kaydi aayaadkaaga jeceshahay',
    listenVerseByVerse: 'Aayad aayad u dhageyso',
    orFullSurah: 'ama suuro buuxda',
    fullSurahs: 'suurado buuxa',
    uthmaniScript: 'Quraanka Qoraalka Cusmaan',
    bismillah: 'Magaca Eebe Naxariis badane Naxariis badan',
    bookOfAllah: 'Kitaabka Eebe',
    readListenReflect: 'Akhri, dhageyso, oo ka fikir aayaadka Eebe',
    juz: 'Juzuc',
    athkarAndDuas: 'Xasuusta iyo Ducada',
    electronicMushaf: 'Musxafka Elektaroonigga',
    allRightsReserved: 'Dhammaan xuquuqda waa la ilaashayaa',
    trustedTafsirsList: 'Tafsiir la aamino: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Turjumaad',
    ttsWarning: 'Ogeysiis: Codku wuxuu ku guuldareysmi karaa si sax ah u ku hadlidda qaar ka mid ah ereyada Islaamka',
  },
  sw: {
    title: 'Qurani Tukufu',
    quran: 'Qurani',
    holyQuran: 'Qurani Tukufu',
    home: 'Nyumbani',
    index: 'Fahirisi',
    settings: 'Mipangilio',
    search: 'Tafuta',
    searchPlaceholder: 'Tafuta sura...',
    athkar: 'Adhkari na Dua',
    appearance: 'Mwonekano',
    lightMode: 'Hali ya Mwanga',
    darkMode: 'Hali ya Giza',
    language: 'Lugha',
    about: 'Kuhusu Programu',
    aboutText: 'Programu ya Qurani yenye Tafsiri 14 zinazokubalika na wasomaji 6 mashuhuri.',
    quickNavigation: 'Uongozaji Haraka',
    surahIndex: 'Fahirisi ya Sura',
    browseSurahs: 'Vinjari Sura za Qurani Tukufu',
    dragToScroll: 'Buruta ili kusogea au tumia mishale',
    viewFullIndex: 'Ona Fahirisi Kamili',
    verse: 'aya',
    verses: 'aya',
    meccan: 'Makkiya',
    medinan: 'Madaniya',
    available: 'Inapatikana',
    surah: 'Sura',
    tafsir: 'Tafsiri',
    tafsirSource: 'Chanzo cha Tafsiri',
    compareTafsirs: 'Linganisha Tafsiri',
    hideTafsir: 'Ficha Tafsiri',
    showTafsir: 'Onyesha Tafsiri',
    benefits: 'Faida',
    aboutSurah: 'Kuhusu Sura Hii',
    listenToRecitation: 'Sikiliza kila aya kutoka kwa wasomaji 6 tofauti',
    reciters: 'wasomaji',
    features: 'Vipengele',
    allInOnePlace: 'Kila kitu mahali pamoja',
    comprehensiveApp: 'Programu kamili ya Qurani: kusoma, kusikiliza na tafsiri',
    trustedTafsirs: 'Tafsiri zinazokubalika',
    fromMajorBooks: 'Kutoka vitabu vikuu vya Tafsiri',
    distinguishedReciters: 'wasomaji mashuhuri',
    beautifulRecitations: 'Usomaji mzuri',
    advancedSearch: 'Utafutaji wa Hali ya Juu',
    searchInVerses: 'Tafuta katika aya na Tafsiri',
    favorites: 'Vipendwa',
    saveYourFavorites: 'Hifadhi aya unazopenda',
    listenVerseByVerse: 'Sikiliza aya kwa aya',
    orFullSurah: 'au sura kamili',
    fullSurahs: 'sura kamili',
    uthmaniScript: 'Qurani kwa Maandishi ya Uthmani',
    bismillah: 'Kwa jina la Mwenyezi Mungu, Mwingi wa rehema, Mwenye kurehemu',
    bookOfAllah: 'Kitabu cha Allah',
    readListenReflect: 'Soma, sikiliza na tafakari aya za Allah',
    juz: 'Juzuu',
    athkarAndDuas: 'Adhkari na Dua',
    electronicMushaf: 'Msahafu wa Kielektroniki',
    allRightsReserved: 'Haki zote zimehifadhiwa',
    trustedTafsirsList: 'Tafsiri Zinazokubalika: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Tafsiri',
    ttsWarning: 'Kumbuka: Sauti inaweza kutotamka kwa usahihi baadhi ya istilahi za Kiislamu',
  },
  ha: {
    title: "Alƙur'ani Mai Tsarki",
    quran: "Alƙur'ani",
    holyQuran: "Alƙur'ani Mai Tsarki",
    home: 'Gida',
    index: 'Jerin Abubuwa',
    settings: 'Saituna',
    search: 'Bincika',
    searchPlaceholder: 'Bincika surori...',
    athkar: 'Azkar da Addu\'a',
    appearance: 'Bayyanar',
    lightMode: 'Yanayin Haske',
    darkMode: 'Yanayin Duhu',
    language: 'Harshe',
    about: 'Game da App',
    aboutText: "Manhajan Alƙur'ani mai Tafsiri 14 amantattu da Maqarai 6 shahararru.",
    quickNavigation: 'Tafiya Sauri',
    surahIndex: 'Jerin Surori',
    browseSurahs: "Duba Surorin Alƙur'ani Mai Tsarki",
    dragToScroll: 'Ja don gungura ko yi amfani da kibiyoyi',
    viewFullIndex: 'Duba Cikakken Jerin',
    verse: 'aya',
    verses: 'ayoyi',
    meccan: 'Makkiyyah',
    medinan: 'Madaniyyah',
    available: 'Akwai',
    surah: 'Suratu',
    tafsir: 'Tafsiri',
    tafsirSource: 'Tushen Tafsiri',
    compareTafsirs: 'Kwatanta Tafsirai',
    hideTafsir: 'Ɓoye Tafsiri',
    showTafsir: 'Nuna Tafsiri',
    benefits: 'Amfani',
    aboutSurah: 'Game da Wannan Suratu',
    listenToRecitation: 'Saurari kowace aya daga Maqarai 6 daban-daban',
    reciters: 'Maqarai',
    features: 'Abubuwan da ke ciki',
    allInOnePlace: 'Duk a wuri ɗaya',
    comprehensiveApp: "Cikakken manhajan Alƙur'ani: karantawa, sauraro da tafsiri",
    trustedTafsirs: 'Tafsiri amantattu',
    fromMajorBooks: 'Daga manyan littattafan Tafsiri',
    distinguishedReciters: 'Maqarai shahararru',
    beautifulRecitations: 'Kyawawan Karatun',
    advancedSearch: 'Binciken Ci gaba',
    searchInVerses: 'Bincika a ayoyi da Tafsirai',
    favorites: 'Abubuwan da Ake So',
    saveYourFavorites: 'Ajiye ayoyin da kake so',
    listenVerseByVerse: 'Saurari aya-aya',
    orFullSurah: 'ko cikakkiyar suratu',
    fullSurahs: 'cikakkun surori',
    uthmaniScript: "Alƙur'ani a Rubutun Uthmani",
    bismillah: 'Da sunan Allah, Mai rahama, Mai jin ƙai',
    bookOfAllah: 'Littafin Allah',
    readListenReflect: 'Karanta, saurara, kuma yi tunani akan ayoyin Allah',
    juz: "Juz'i",
    athkarAndDuas: 'Azkar da Addu\'a',
    electronicMushaf: 'Mushaf na Lantarki',
    allRightsReserved: 'An kiyaye duk haƙƙoƙi',
    trustedTafsirsList: 'Tafsiri Amantattu: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Fassara',
    ttsWarning: 'Lura: Audio na iya kasa furta wasu kalmomin Musulunci daidai',
  },
  yo: {
    title: 'Al-Kurani Mimọ',
    quran: 'Al-Kurani',
    holyQuran: 'Al-Kurani Mimọ',
    home: 'Ile',
    index: 'Atọka',
    settings: 'Ètò',
    search: 'Ṣàwárí',
    searchPlaceholder: 'Ṣàwárí awọn sura...',
    athkar: 'Adhkar àti Duas',
    appearance: 'Ìrísí',
    lightMode: 'Ipò Ìmọ́lẹ̀',
    darkMode: 'Ipò Òkùnkùn',
    language: 'Èdè',
    about: 'Nípa App',
    aboutText: 'App Al-Kurani pẹ̀lú Tafsir 14 tí a gbẹ́kẹ̀lé àti awọn olùkàwé 6 olókìkí.',
    quickNavigation: 'Ìrìn-àjò Kíákíá',
    surahIndex: 'Àtòjọ Sura',
    browseSurahs: 'Ṣàwárí Awọn Sura ti Al-Kurani Mimọ',
    dragToScroll: 'Fa láti yí padà tàbí lo awọn ọfà',
    viewFullIndex: 'Wo Àtòjọ Kíkún',
    verse: 'aya',
    verses: 'aya',
    meccan: 'Makkiyyah',
    medinan: 'Madaniyyah',
    available: 'Wà',
    surah: 'Sura',
    tafsir: 'Tafsir',
    tafsirSource: 'Orísun Tafsir',
    compareTafsirs: 'Ṣe àfiwé Tafsir',
    hideTafsir: 'Fi Tafsir pamọ́',
    showTafsir: 'Ṣàfihàn Tafsir',
    benefits: 'Àǹfààní',
    aboutSurah: 'Nípa Sura yìí',
    listenToRecitation: 'Gbọ́ aya kọ̀ọ̀kan láti ọ̀dọ̀ olùkàwé 6 oríṣiríṣi',
    reciters: 'olùkàwé',
    features: 'Àwọn Ẹ̀yà',
    allInOnePlace: 'Gbogbo rẹ̀ ní ibi kan',
    comprehensiveApp: 'App Al-Kurani tó pé: kíkà, gbígbọ́ àti àlàyé',
    trustedTafsirs: 'Tafsir tí a gbẹ́kẹ̀lé',
    fromMajorBooks: 'Láti inú àwọn ìwé Tafsir pàtàkì',
    distinguishedReciters: 'awọn olùkàwé olókìkí',
    beautifulRecitations: 'Kíkà tó dára',
    advancedSearch: 'Àwárí Tó Jinlẹ̀',
    searchInVerses: 'Ṣàwárí nínú aya àti Tafsir',
    favorites: 'Àwọn Àyànfẹ́',
    saveYourFavorites: 'Fi àwọn aya àyànfẹ́ rẹ pamọ́',
    listenVerseByVerse: 'Gbọ́ aya kan síi aya kan',
    orFullSurah: 'tàbí sura kíkún',
    fullSurahs: 'sura kíkún',
    uthmaniScript: 'Al-Kurani ní Ìkọ̀wé Uthmani',
    bismillah: 'Ní orúkọ Allah, Aláàánú, Oníkẹ̀ẹ́',
    bookOfAllah: 'Ìwé Allah',
    readListenReflect: 'Ka, gbọ́, kí o sì ronú lórí àwọn aya Allah',
    juz: 'Juz',
    athkarAndDuas: 'Adhkar àti Duas',
    electronicMushaf: 'Mushaf Ẹ̀rọ',
    allRightsReserved: 'Gbogbo ẹ̀tọ́ ni a ní',
    trustedTafsirsList: 'Tafsir Tí A Gbẹ́kẹ̀lé: Ibn Kathir | Tabari | Saadi | Muyassar | Jalalayn',
    translation: 'Ìtumọ̀',
    ttsWarning: 'Àkíyèsí: Ohùn le ma sọ àwọn ọ̀rọ̀ Islam kan tọ́',
  },
  ml: {
    title: 'വിശുദ്ധ ഖുർആൻ',
    quran: 'ഖുർആൻ',
    holyQuran: 'വിശുദ്ധ ഖുർആൻ',
    home: 'ഹോം',
    index: 'സൂചിക',
    settings: 'ക്രമീകരണങ്ങൾ',
    search: 'തിരയുക',
    searchPlaceholder: 'സൂറകൾ തിരയുക...',
    athkar: 'അദ്കാർ & ദുആ',
    appearance: 'രൂപം',
    lightMode: 'ലൈറ്റ് മോഡ്',
    darkMode: 'ഡാർക്ക് മോഡ്',
    language: 'ഭാഷ',
    about: 'ആപ്പിനെക്കുറിച്ച്',
    aboutText: '14 വിശ്വസനീയ തഫ്‌സീറുകളും 6 പ്രശസ്ത ഖാരിമാരുമുള്ള ഖുർആൻ ആപ്പ്.',
    quickNavigation: 'ദ്രുത നാവിഗേഷൻ',
    surahIndex: 'സൂറ സൂചിക',
    browseSurahs: 'വിശുദ്ധ ഖുർആന്റെ സൂറകൾ ബ്രൗസ് ചെയ്യുക',
    dragToScroll: 'സ്ക്രോൾ ചെയ്യാൻ വലിക്കുക അല്ലെങ്കിൽ അമ്പടയാളങ്ങൾ ഉപയോഗിക്കുക',
    viewFullIndex: 'മുഴുവൻ സൂചിക കാണുക',
    verse: 'ആയത്ത്',
    verses: 'ആയത്തുകൾ',
    meccan: 'മക്കി',
    medinan: 'മദനി',
    available: 'ലഭ്യം',
    surah: 'സൂറ',
    tafsir: 'തഫ്‌സീർ',
    tafsirSource: 'തഫ്‌സീർ ഉറവിടം',
    compareTafsirs: 'തഫ്‌സീറുകൾ താരതമ്യം ചെയ്യുക',
    hideTafsir: 'തഫ്‌സീർ മറയ്ക്കുക',
    showTafsir: 'തഫ്‌സീർ കാണിക്കുക',
    benefits: 'ഗുണങ്ങൾ',
    aboutSurah: 'ഈ സൂറയെക്കുറിച്ച്',
    listenToRecitation: '6 വ്യത്യസ്ത ഖാരിമാരിൽ നിന്ന് ഓരോ ആയത്തും കേൾക്കുക',
    reciters: 'ഖാരിമാർ',
    features: 'സവിശേഷതകൾ',
    allInOnePlace: 'എല്ലാം ഒരിടത്ത്',
    comprehensiveApp: 'സമഗ്ര ഖുർആൻ ആപ്പ്: വായന, ശ്രവണം, വ്യാഖ്യാനം',
    trustedTafsirs: 'വിശ്വസനീയ തഫ്‌സീറുകൾ',
    fromMajorBooks: 'പ്രധാന തഫ്‌സീർ ഗ്രന്ഥങ്ങളിൽ നിന്ന്',
    distinguishedReciters: 'പ്രശസ്ത ഖാരിമാർ',
    beautifulRecitations: 'മനോഹരമായ പാരായണങ്ങൾ',
    advancedSearch: 'വിപുലമായ തിരയൽ',
    searchInVerses: 'ആയത്തുകളിലും തഫ്‌സീറുകളിലും തിരയുക',
    favorites: 'പ്രിയപ്പെട്ടവ',
    saveYourFavorites: 'നിങ്ങളുടെ പ്രിയപ്പെട്ട ആയത്തുകൾ സംരക്ഷിക്കുക',
    listenVerseByVerse: 'ആയത്ത് ആയത്തായി കേൾക്കുക',
    orFullSurah: 'അല്ലെങ്കിൽ മുഴുവൻ സൂറ',
    fullSurahs: 'മുഴുവൻ സൂറകൾ',
    uthmaniScript: 'ഉസ്മാനി ലിപിയിലുള്ള ഖുർആൻ',
    bismillah: 'പരമകാരുണികനും കരുണാനിധിയുമായ അല്ലാഹുവിന്റെ നാമത്തിൽ',
    bookOfAllah: 'അല്ലാഹുവിന്റെ ഗ്രന്ഥം',
    readListenReflect: 'അല്ലാഹുവിന്റെ ആയത്തുകൾ വായിക്കുക, കേൾക്കുക, ചിന്തിക്കുക',
    juz: 'ജുസ്‌അ്',
    athkarAndDuas: 'അദ്കാർ & ദുആ',
    electronicMushaf: 'ഇലക്ട്രോണിക് മുസ്ഹഫ്',
    allRightsReserved: 'എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം',
    trustedTafsirsList: 'വിശ്വസനീയ തഫ്‌സീറുകൾ: ഇബ്നു കസീർ | തബരി | സഅദി | മുയസ്സർ | ജലാലൈൻ',
    translation: 'വിവർത്തനം',
    ttsWarning: 'ശ്രദ്ധിക്കുക: ചില ഇസ്‌ലാമിക പദങ്ങൾ ഓഡിയോ ശരിയായി ഉച്ചരിച്ചേക്കില്ല',
  },
  ta: {
    title: 'புனித குர்ஆன்',
    quran: 'குர்ஆன்',
    holyQuran: 'புனித குர்ஆன்',
    home: 'முகப்பு',
    index: 'அட்டவணை',
    settings: 'அமைப்புகள்',
    search: 'தேடு',
    searchPlaceholder: 'சூராக்களைத் தேடுங்கள்...',
    athkar: 'திக்ர் & துஆக்கள்',
    appearance: 'தோற்றம்',
    lightMode: 'ஒளி பயன்முறை',
    darkMode: 'இருள் பயன்முறை',
    language: 'மொழி',
    about: 'பயன்பாடு பற்றி',
    aboutText: '14 நம்பகமான தஃப்சீர்கள் மற்றும் 6 புகழ்பெற்ற காரிகள் கொண்ட குர்ஆன் பயன்பாடு.',
    quickNavigation: 'விரைவு வழிசெலுத்தல்',
    surahIndex: 'சூரா அட்டவணை',
    browseSurahs: 'புனித குர்ஆனின் சூராக்களை உலாவுங்கள்',
    dragToScroll: 'உருட்ட இழுக்கவும் அல்லது அம்புக்குறிகளைப் பயன்படுத்தவும்',
    viewFullIndex: 'முழு அட்டவணையைக் காண்க',
    verse: 'ஆயத்',
    verses: 'ஆயத்துகள்',
    meccan: 'மக்கி',
    medinan: 'மதனி',
    available: 'கிடைக்கிறது',
    surah: 'சூரா',
    tafsir: 'தஃப்சீர்',
    tafsirSource: 'தஃப்சீர் ஆதாரம்',
    compareTafsirs: 'தஃப்சீர்களை ஒப்பிடுக',
    hideTafsir: 'தஃப்சீர் மறை',
    showTafsir: 'தஃப்சீர் காட்டு',
    benefits: 'நன்மைகள்',
    aboutSurah: 'இந்த சூரா பற்றி',
    listenToRecitation: '6 வெவ்வேறு காரிகளிடமிருந்து ஒவ்வொரு ஆயத்தையும் கேளுங்கள்',
    reciters: 'காரிகள்',
    features: 'அம்சங்கள்',
    allInOnePlace: 'அனைத்தும் ஒரே இடத்தில்',
    comprehensiveApp: 'முழுமையான குர்ஆன் பயன்பாடு: படித்தல், கேட்டல், விளக்கம்',
    trustedTafsirs: 'நம்பகமான தஃப்சீர்கள்',
    fromMajorBooks: 'முக்கிய தஃப்சீர் நூல்களிலிருந்து',
    distinguishedReciters: 'புகழ்பெற்ற காரிகள்',
    beautifulRecitations: 'அழகான ஓதல்கள்',
    advancedSearch: 'மேம்பட்ட தேடல்',
    searchInVerses: 'ஆயத்துகள் மற்றும் தஃப்சீர்களில் தேடுங்கள்',
    favorites: 'பிடித்தவை',
    saveYourFavorites: 'உங்கள் பிடித்த ஆயத்துகளைச் சேமியுங்கள்',
    listenVerseByVerse: 'ஆயத் ஆயத்தாகக் கேளுங்கள்',
    orFullSurah: 'அல்லது முழு சூரா',
    fullSurahs: 'முழு சூராக்கள்',
    uthmaniScript: 'உஸ்மானி எழுத்தில் குர்ஆன்',
    bismillah: 'அளவற்ற அருளாளன், நிகரற்ற அன்புடையோன் அல்லாஹ்வின் பெயரால்',
    bookOfAllah: 'அல்லாஹ்வின் வேதம்',
    readListenReflect: 'அல்லாஹ்வின் ஆயத்துகளைப் படியுங்கள், கேளுங்கள், சிந்தியுங்கள்',
    juz: 'ஜுஸ்',
    athkarAndDuas: 'திக்ர் & துஆக்கள்',
    electronicMushaf: 'மின்னணு முஸ்ஹஃப்',
    allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை',
    trustedTafsirsList: 'நம்பகமான தஃப்சீர்கள்: இப்னு கதீர் | தபரி | ஸஃதி | முயஸ்ஸர் | ஜலாலைன்',
    translation: 'மொழிபெயர்ப்பு',
    ttsWarning: 'குறிப்பு: சில இஸ்லாமிய சொற்களை ஒலி சரியாக உச்சரிக்காமல் போகலாம்',
  },
  te: {
    title: 'పవిత్ర ఖురాన్',
    quran: 'ఖురాన్',
    holyQuran: 'పవిత్ర ఖురాన్',
    home: 'హోమ్',
    index: 'సూచిక',
    settings: 'సెట్టింగ్‌లు',
    search: 'వెతుకు',
    searchPlaceholder: 'సూరాలను వెతకండి...',
    athkar: 'అధ్కార్ & దువాలు',
    appearance: 'రూపం',
    lightMode: 'లైట్ మోడ్',
    darkMode: 'డార్క్ మోడ్',
    language: 'భాష',
    about: 'యాప్ గురించి',
    aboutText: '14 విశ్వసనీయ తఫ్సీర్‌లు మరియు 6 ప్రముఖ ఖారీలతో ఖురాన్ యాప్.',
    quickNavigation: 'త్వరిత నావిగేషన్',
    surahIndex: 'సూరా సూచిక',
    browseSurahs: 'పవిత్ర ఖురాన్ సూరాలను బ్రౌజ్ చేయండి',
    dragToScroll: 'స్క్రోల్ చేయడానికి లాగండి లేదా బాణాలు ఉపయోగించండి',
    viewFullIndex: 'పూర్తి సూచిక చూడండి',
    verse: 'ఆయత్',
    verses: 'ఆయత్‌లు',
    meccan: 'మక్కీ',
    medinan: 'మదనీ',
    available: 'అందుబాటులో ఉంది',
    surah: 'సూరా',
    tafsir: 'తఫ్సీర్',
    tafsirSource: 'తఫ్సీర్ మూలం',
    compareTafsirs: 'తఫ్సీర్‌లను పోల్చండి',
    hideTafsir: 'తఫ్సీర్ దాచు',
    showTafsir: 'తఫ్సీర్ చూపించు',
    benefits: 'ప్రయోజనాలు',
    aboutSurah: 'ఈ సూరా గురించి',
    listenToRecitation: '6 వేర్వేరు ఖారీల నుండి ప్రతి ఆయత్ వినండి',
    reciters: 'ఖారీలు',
    features: 'ఫీచర్లు',
    allInOnePlace: 'అన్నీ ఒకే చోట',
    comprehensiveApp: 'సమగ్ర ఖురాన్ యాప్: చదవడం, వినడం, వ్యాఖ్యానం',
    trustedTafsirs: 'విశ్వసనీయ తఫ్సీర్‌లు',
    fromMajorBooks: 'ప్రధాన తఫ్సీర్ పుస్తకాల నుండి',
    distinguishedReciters: 'ప్రముఖ ఖారీలు',
    beautifulRecitations: 'అందమైన పారాయణాలు',
    advancedSearch: 'అధునాతన శోధన',
    searchInVerses: 'ఆయత్‌లు మరియు తఫ్సీర్‌లలో వెతకండి',
    favorites: 'ఇష్టమైనవి',
    saveYourFavorites: 'మీ ఇష్టమైన ఆయత్‌లను సేవ్ చేయండి',
    listenVerseByVerse: 'ఆయత్ ఆయత్‌గా వినండి',
    orFullSurah: 'లేదా పూర్తి సూరా',
    fullSurahs: 'పూర్తి సూరాలు',
    uthmaniScript: 'ఉస్మానీ లిపిలో ఖురాన్',
    bismillah: 'కరుణామయుడు, దయామయుడు అయిన అల్లాహ్ పేరుతో',
    bookOfAllah: 'అల్లాహ్ గ్రంథం',
    readListenReflect: 'అల్లాహ్ ఆయత్‌లను చదవండి, వినండి, ఆలోచించండి',
    juz: 'జుజ్',
    athkarAndDuas: 'అధ్కార్ & దువాలు',
    electronicMushaf: 'ఎలక్ట్రానిక్ ముస్హఫ్',
    allRightsReserved: 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి',
    trustedTafsirsList: 'విశ్వసనీయ తఫ్సీర్‌లు: ఇబ్న్ కథీర్ | తబరీ | సాదీ | ముయస్సర్ | జలాలైన్',
    translation: 'అనువాదం',
    ttsWarning: 'గమనిక: కొన్ని ఇస్లామిక్ పదాలను ఆడియో సరిగ్గా ఉచ్చరించకపోవచ్చు',
  },
  si: {
    title: 'ශුද්ධ වූ කුර්ආනය',
    quran: 'කුර්ආනය',
    holyQuran: 'ශුද්ධ වූ කුර්ආනය',
    home: 'මුල් පිටුව',
    index: 'සූචිය',
    settings: 'සැකසුම්',
    search: 'සොයන්න',
    searchPlaceholder: 'සූරා සොයන්න...',
    athkar: 'අද්කාර් සහ දුආ',
    appearance: 'පෙනුම',
    lightMode: 'ලයිට් මෝඩ්',
    darkMode: 'ඩාර්ක් මෝඩ්',
    language: 'භාෂාව',
    about: 'යෙදුම ගැන',
    aboutText: 'විශ්වාසනීය තෆ්සීර් 14ක් සහ ප්‍රසිද්ධ කාරිලා 6 දෙනෙකු සහිත කුර්ආන් යෙදුම.',
    quickNavigation: 'ඉක්මන් සංචාලනය',
    surahIndex: 'සූරා සූචිය',
    browseSurahs: 'ශුද්ධ කුර්ආනයේ සූරා බ්‍රවුස් කරන්න',
    dragToScroll: 'අනුචලනය සඳහා ඇදගෙන යන්න හෝ ඊතල භාවිතා කරන්න',
    viewFullIndex: 'සම්පූර්ණ සූචිය බලන්න',
    verse: 'ආයත්',
    verses: 'ආයත්',
    meccan: 'මක්කි',
    medinan: 'මදනී',
    available: 'ලබා ගත හැක',
    surah: 'සූරා',
    tafsir: 'තෆ්සීර්',
    tafsirSource: 'තෆ්සීර් මූලාශ්‍රය',
    compareTafsirs: 'තෆ්සීර් සංසන්දනය කරන්න',
    hideTafsir: 'තෆ්සීර් සඟවන්න',
    showTafsir: 'තෆ්සීර් පෙන්වන්න',
    benefits: 'ප්‍රතිලාභ',
    aboutSurah: 'මෙම සූරාව ගැන',
    listenToRecitation: 'කාරිලා 6 දෙනෙකුගෙන් සෑම ආයතයක්ම අසන්න',
    reciters: 'කාරිලා',
    features: 'විශේෂාංග',
    allInOnePlace: 'සියල්ල එක තැනක',
    comprehensiveApp: 'සම්පූර්ණ කුර්ආන් යෙදුම: කියවීම, ශ්‍රවණය, අර්ථකථනය',
    trustedTafsirs: 'විශ්වාසනීය තෆ්සීර්',
    fromMajorBooks: 'ප්‍රධාන තෆ්සීර් ග්‍රන්ථ වලින්',
    distinguishedReciters: 'ප්‍රසිද්ධ කාරිලා',
    beautifulRecitations: 'අලංකාර පාරායණ',
    advancedSearch: 'උසස් සෙවුම',
    searchInVerses: 'ආයත් සහ තෆ්සීර් වල සොයන්න',
    favorites: 'ප්‍රියතමයන්',
    saveYourFavorites: 'ඔබේ ප්‍රියතම ආයත් සුරකින්න',
    listenVerseByVerse: 'ආයතෙන් ආයතය අසන්න',
    orFullSurah: 'හෝ සම්පූර්ණ සූරාව',
    fullSurahs: 'සම්පූර්ණ සූරා',
    uthmaniScript: 'උස්මානි අකුරින් කුර්ආනය',
    bismillah: 'අසීමිත කරුණාව, අසීමිත දයාව ඇති අල්ලාහ්ගේ නාමයෙන්',
    bookOfAllah: 'අල්ලාහ්ගේ ග්‍රන්ථය',
    readListenReflect: 'අල්ලාහ්ගේ ආයත් කියවන්න, අසන්න, සිතන්න',
    juz: 'ජුස්',
    athkarAndDuas: 'අද්කාර් සහ දුආ',
    electronicMushaf: 'විද්‍යුත් මුස්හෆ්',
    allRightsReserved: 'සියලු හිමිකම් ඇවිරිණි',
    trustedTafsirsList: 'විශ්වාසනීය තෆ්සීර්: ඉබ්නු කසීර් | තබරී | සආදී | මුයස්සර් | ජලාලයින්',
    translation: 'පරිවර්තනය',
    ttsWarning: 'සටහන: සමහර ඉස්ලාමීය පද ශ්‍රව්‍ය නිවැරදිව උච්චාරණය නොකළ හැක',
  },
  ne: {
    title: 'पवित्र कुरान',
    quran: 'कुरान',
    holyQuran: 'पवित्र कुरान',
    home: 'गृहपृष्ठ',
    index: 'सूचि',
    settings: 'सेटिङ्हरू',
    search: 'खोज्नुहोस्',
    searchPlaceholder: 'सूरा खोज्नुहोस्...',
    athkar: 'अद्कार र दुआ',
    appearance: 'उपस्थिति',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    about: 'एप बारेमा',
    aboutText: '१४ विश्वसनीय तफ्सीर र ६ प्रतिष्ठित कारीहरू सहित कुरान एप।',
    quickNavigation: 'द्रुत नेभिगेसन',
    surahIndex: 'सूरा सूचि',
    browseSurahs: 'पवित्र कुरानका सूराहरू हेर्नुहोस्',
    dragToScroll: 'स्क्रोल गर्न तान्नुहोस् वा तीरहरू प्रयोग गर्नुहोस्',
    viewFullIndex: 'पूर्ण सूचि हेर्नुहोस्',
    verse: 'आयत',
    verses: 'आयतहरू',
    meccan: 'मक्की',
    medinan: 'मदनी',
    available: 'उपलब्ध',
    surah: 'सूरा',
    tafsir: 'तफ्सीर',
    tafsirSource: 'तफ्सीर स्रोत',
    compareTafsirs: 'तफ्सीरहरू तुलना गर्नुहोस्',
    hideTafsir: 'तफ्सीर लुकाउनुहोस्',
    showTafsir: 'तफ्सीर देखाउनुहोस्',
    benefits: 'फाइदाहरू',
    aboutSurah: 'यो सूरा बारेमा',
    listenToRecitation: '६ विभिन्न कारीहरूबाट प्रत्येक आयत सुन्नुहोस्',
    reciters: 'कारी',
    features: 'विशेषताहरू',
    allInOnePlace: 'सबै एकै ठाउँमा',
    comprehensiveApp: 'व्यापक कुरान एप: पढ्ने, सुन्ने र व्याख्या',
    trustedTafsirs: 'विश्वसनीय तफ्सीरहरू',
    fromMajorBooks: 'प्रमुख तफ्सीर पुस्तकहरूबाट',
    distinguishedReciters: 'प्रतिष्ठित कारीहरू',
    beautifulRecitations: 'सुन्दर पाठहरू',
    advancedSearch: 'उन्नत खोज',
    searchInVerses: 'आयत र तफ्सीरहरूमा खोज्नुहोस्',
    favorites: 'मनपर्नेहरू',
    saveYourFavorites: 'आफ्ना मनपर्ने आयतहरू सुरक्षित गर्नुहोस्',
    listenVerseByVerse: 'आयत-आयत सुन्नुहोस्',
    orFullSurah: 'वा पूर्ण सूरा',
    fullSurahs: 'पूर्ण सूराहरू',
    uthmaniScript: 'उस्मानी लिपिमा कुरान',
    bismillah: 'अत्यन्त दयालु र कृपालु अल्लाहको नाममा',
    bookOfAllah: 'अल्लाहको किताब',
    readListenReflect: 'अल्लाहका आयतहरू पढ्नुहोस्, सुन्नुहोस् र विचार गर्नुहोस्',
    juz: 'जुज',
    athkarAndDuas: 'अद्कार र दुआ',
    electronicMushaf: 'इलेक्ट्रोनिक मुसहफ',
    allRightsReserved: 'सबै अधिकार सुरक्षित',
    trustedTafsirsList: 'विश्वसनीय तफ्सीरहरू: इब्न कसीर | तबरी | साअदी | मुयस्सर | जलालैन',
    translation: 'अनुवाद',
    ttsWarning: 'नोट: अडियोले केही इस्लामिक शब्दहरू सही उच्चारण नगर्न सक्छ',
  },
  dv: {
    title: 'ކީރިތި ޤުރުއާން',
    quran: 'ޤުރުއާން',
    holyQuran: 'ކީރިތި ޤުރުއާން',
    home: 'ފުރަތަމަ ޞަފުޙާ',
    index: 'ފިހުރިސްތު',
    settings: 'ސެޓިންގްސް',
    search: 'ހޯދާ',
    searchPlaceholder: 'ސޫރަތް ހޯދާ...',
    athkar: 'ޒިކުރު އަދި ދުޢާ',
    appearance: 'ސިފަ',
    lightMode: 'ލައިޓް މޯޑް',
    darkMode: 'ޑާކް މޯޑް',
    language: 'ބަސް',
    about: 'އެޕް އާ ބެހޭގޮތުން',
    aboutText: '14 އިތުބާރުކުރެވޭ ތަފްސީރާއި 6 މަޝްހޫރު ޤާރީންނާއެކު ޤުރުއާން އެޕް.',
    quickNavigation: 'އަވަސް ނެވިގޭޝަން',
    surahIndex: 'ސޫރަތް ފިހުރިސްތު',
    browseSurahs: 'ކީރިތި ޤުރުއާންގެ ސޫރަތްތައް ބައްލަވާ',
    dragToScroll: 'ސްކްރޯލް ކުރުމަށް ޑްރެގް ކުރައްވާ ނުވަތަ ތީރުތައް ބޭނުންކުރައްވާ',
    viewFullIndex: 'ފުރިހަމަ ފިހުރިސްތު ބައްލަވާ',
    verse: 'އާޔަތް',
    verses: 'އާޔަތް',
    meccan: 'މައްކީ',
    medinan: 'މަދަނީ',
    available: 'ލިބެން އެބަހުރި',
    surah: 'ސޫރަތް',
    tafsir: 'ތަފްސީރު',
    tafsirSource: 'ތަފްސީރުގެ މަޞްދަރު',
    compareTafsirs: 'ތަފްސީރުތައް އަޅާކިޔާ',
    hideTafsir: 'ތަފްސީރު ފޮރުވާ',
    showTafsir: 'ތަފްސީރު ދައްކާ',
    benefits: 'ފައިދާތައް',
    aboutSurah: 'މި ސޫރަތާ ބެހޭގޮތުން',
    listenToRecitation: '6 ތަފާތު ޤާރީންގެ ކިބައިން ކޮންމެ އާޔަތެއް އަޑުއައްސަވާ',
    reciters: 'ޤާރީން',
    features: 'ފީޗާސް',
    allInOnePlace: 'ހުރިހާ އެއްޗެއް އެއްތަނެއްގައި',
    comprehensiveApp: 'ފުރިހަމަ ޤުރުއާން އެޕް: ކިޔެވުން، އަޑުއެހުން، ތަފްސީރު',
    trustedTafsirs: 'އިތުބާރުކުރެވޭ ތަފްސީރު',
    fromMajorBooks: 'މައި ތަފްސީރު ފޮތްތަކުން',
    distinguishedReciters: 'މަޝްހޫރު ޤާރީން',
    beautifulRecitations: 'ރީތި ކިޔެވުންތައް',
    advancedSearch: 'އެޑްވާންސް ސާޗް',
    searchInVerses: 'އާޔަތްތަކާއި ތަފްސީރުތަކުން ހޯދާ',
    favorites: 'ފެވަރިޓްސް',
    saveYourFavorites: 'ތިބާގެ ފެވަރިޓް އާޔަތްތައް ސޭވް ކުރައްވާ',
    listenVerseByVerse: 'އާޔަތުން އާޔަތް އަޑުއައްސަވާ',
    orFullSurah: 'ނުވަތަ ފުރިހަމަ ސޫރަތް',
    fullSurahs: 'ފުރިހަމަ ސޫރަތްތައް',
    uthmaniScript: 'ޢުޘްމާނީ ލިޔުމުގައި ޤުރުއާން',
    bismillah: 'ރަޙްމާންވަންތަ ރަޙީމްވަންތަ ﷲ ގެ އިސްމުފުޅުން',
    bookOfAllah: 'ﷲ ގެ ފޮތް',
    readListenReflect: 'ﷲ ގެ އާޔަތްތައް ކިޔަވާ، އަޑުއައްސަވާ، ވިސްނާ',
    juz: 'ޖުޒު',
    athkarAndDuas: 'ޒިކުރު އަދި ދުޢާ',
    electronicMushaf: 'އިލެކްޓްރޯނިކް މުޞްޙަފް',
    allRightsReserved: 'ހުރިހާ ޙައްޤުތަކެއް ރައްކާތެރިކޮށްފައި',
    trustedTafsirsList: 'އިތުބާރުކުރެވޭ ތަފްސީރު: އިބްން ކަޘީރު | ޠަބަރީ | ސަޢުދީ | މުޔައްސަރު | ޖަލާލައިން',
    translation: 'ތަރުޖަމާ',
    ttsWarning: 'ނޯޓް: ބައެއް އިސްލާމީ ބަސްތައް އޯޑިއޯއިން ރަނގަޅަށް ކިޔައިނުދީފާނެ',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: TranslationStrings;
  isRtl: boolean;
  dir: 'rtl' | 'ltr';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const rtlLanguages: Language[] = ['ar', 'ur', 'fa', 'dv'];

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('quran-app-language');
    return (saved as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('quran-app-language', lang);
  };

  const isRtl = rtlLanguages.includes(language);
  const dir = isRtl ? 'rtl' : 'ltr';
  const t = translations[language] || translations.en;

  useEffect(() => {
    document.documentElement.setAttribute('dir', dir);
    document.documentElement.setAttribute('lang', language);
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Helper function to get translation ID for a language
export const getTranslationId = (langCode: Language): number | undefined => {
  const lang = languages.find(l => l.code === langCode);
  return lang?.translationId;
};
